### ISSUE TITLE
https://metacpan.org/pod/perlfunc doesn't point to the *perlfunc.pod* of the current perl release

### ISSUE THREAD

**Issue by bpj** [CPAN-API/metacpan-web#1031]
<https://metacpan.org/pod/perlfunc>

points to

<https://metacpan.org/pod/release/BDFOY/perlbench-0.94/benchmarks/app/perlfunc.pod>

Surely it should point to the *perldoc.pod* of the curreent perl
release?

<https://metacpan.org/pod/release/RJBS/perl-5.18.1/pod/perlfunc.pod>

If this can't be fixed, how should I write an URL to get to the
*perlfunc.pod* of the current perl release, rather than to that
of a specific perl release?

**Comment by ranguard** [comment]
As this is on the wishlist already closing this issue
