### ISSUE TITLE
"Browse" is broken for distros that don't unpack nicely

### ISSUE THREAD

**Issue by zoffixznet** [CPAN-API/metacpan-web#1043]
By "unpack nicely" I mean distros that unpack all their files into the current folder instead of creating one named, e.g. Distro-Foo-Bar-0.1

For example, https://metacpan.org/release/JEFFLEARY/time.piece.cron_0.1 just got uploaded and if you download the tarball http://cpan.metacpan.org/authors/id/J/JE/JEFFLEARY/time.piece.cron_0.1.tar.gz and unpack it, you'll see all the files unpack into the current directory.

If we go to "Browse" feature (https://metacpan.org/source/JEFFLEARY/time.piece.cron_0.1), we'll see `Time/` directory and tests right in there, even though the dist contains `Build.PL`, `lib/` and others.

**Comment by kentfredric** [comment]
Another fun example: https://metacpan.org/release/SFLEX/SF_form_secure_v4.0

The version other than the current one have `browse` doing this:

![sn75](https://cloud.githubusercontent.com/assets/44790/7442751/45b8fc74-f172-11e4-9ce1-8b748126135d.jpg)

And clicking a module in dist overview does 

![sn76](https://cloud.githubusercontent.com/assets/44790/7442753/73f3e900-f172-11e4-97e2-25405ebc727c.jpg)

Or giving file-not-found responses.
