### ISSUE TITLE
bad issues count for new distribution

### ISSUE THREAD

**Issue by karenetheridge** [CPAN-API/metacpan-web#1133]
https://metacpan.org/pod/release/SUKRIA/File-Scan-0.001/lib/File/Scan.pm

newly uploaded 15 minutes ago

The 'issues' link points to github and says there are 3 issues. But there are 0 open+closed issues on github.

**Comment by haarg** [comment]
I believe @rwstauner's recent changes have resolved the issues with the GitHub popup.
