### ISSUE TITLE
PSGI::FAQ is served in Russian

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#1141]
Visiting https://metacpan.org/pod/PSGI::FAQ I get the content of  https://metacpan.org/source/VTI/POD2-RU-PSGI-0.001/lib/POD2/RU/PSGI/FAQ.pod

**Comment by ranguard** [comment]
Not russian any more

**Comment by oalders** [comment]
I suspect this will toggle back to Russian at some point since the last one in wins.

**Comment by karenetheridge** [comment]
I believe @miyagawa can fix this by renaming lib/PSGI/FAQ.pod to lib/PSGI/FAQ.pm with a single-line `package` statement, so he gets PAUSE permissions for that namespace. Then metacpan will be able to tell the difference between the "real" PSGI::FAQ and the Russian version which is just a plain old pod with no attached permissions.
