### ISSUE TITLE
Missing dists

### ISSUE THREAD

**Issue by neilbowers** [CPAN-API/metacpan-web#1149]
The dists listed below are on CPAN, appear in 02packages.details.txt, but don't appear in the releases index on MetaCPAN.

I generated this list by running a [script](https://gist.github.com/neilbowers/10012278) that generates an index of latest releases on CPAN (both developer and non-developer releases), and then comparing with 02packages using PAUSE::Packages.

I wrote a standalone [script](https://gist.github.com/neilbowers/10017803) for doing this check, but it's reporting more dists (roughly 220 instead of the 75 I found last night). And some of these are in fact there, so there's something wrong with the second script / query.

Neil

Ticked packages means there is a know reason (e.g. apostrophe in package name)

- [x] Acme-Cant (K/KC/KCOWGILL/Acme-Cant-0.01.tar.gz)
- [ ] Acme-Schrodinger-Do (R/RO/ROOTKWOK/Acme-Schrodinger-Do-0.04.tar.gz)
- [ ] Array-Sort (W/WI/WILL/Array-Sort-0.02.tar.gz)
- [ ] BGPmon-Analytics-db-1 (B/BG/BGPMON/BGPmon-Analytics-db-1-07.tar.gz)
- [ ] BGPmon-Archiver-2 (B/BG/BGPMON/BGPmon-Archiver-2-10.tar.gz)
- [ ] Bundle-Graphics-ColorNames (R/RR/RRWO/Bundle-Graphics-ColorNames-1.04.tar.gz)
- [ ] Business-OnlinePayment-2CheckOut (A/AK/AKHOBOV/Business-OnlinePayment-2CheckOut-0.02.tar.gz)
- [ ] CPAN-Test-Dummy-Perl5-PackageWithBlock (T/TS/TSIBLEY/CPAN-Test-Dummy-Perl5-PackageWithBlock-0.03.tar.gz)
- [ ] Catalyst-Authentication-Store-DBI (J/JA/JANUS/Catalyst-Authentication-Store-DBI-0.01.tar.gz)
- [ ] Catalyst-Plugin-Authorization-CDBI-GroupToken (S/SS/SSC/Catalyst-Plugin-Authorization-CDBI-GroupToken-0.01.tar.gz)
- [ ] Catalyst-Plugin-Cache-Memcached (B/BO/BOBTFISH/Catalyst-Plugin-Cache-Memcached-0.8.tar.gz)
- [ ] Catalyst-Plugin-ReferingKeyword (A/AS/ASHLEY/Catalyst-Plugin-ReferingKeyword-0.01.tar.gz)
- [ ] Catalyst-View-HTML-Embperl (A/AL/ALET/Catalyst-View-HTML-Embperl-0.01.tar.gz)
- [ ] Catalyst-View-XML-Generator (N/NA/NACHBAUR/Catalyst-View-XML-Generator-0.02.tar.gz)
- [ ] DBD-Cubrid (C/CU/CUBRID/DBD-Cubrid-9.2.0.0001.tar.gz)
- [ ] DHTMLX-Connector (E/ED/EDUARDOW/DHTMLX-Connector-0.002.tar.gz)
- [ ] DHTMLX-Core (E/ED/EDUARDOW/DHTMLX-Core-0.004.tar.gz)
- [ ] Database-Schema-Config (S/SA/SAXJAZMAN/database/Database-Schema-Config-.02.tar.gz)
- [ ] Devel-RegExp (I/IL/ILYAZ/modules/Devel-RegExp-0.1.tar.gz)
- [ ] Dotiac (M/MA/MALUKU/dotiac/Dotiac-0.8.tar.gz)
- [ ] Email-LocalDelivery-Store (B/BD/BDWELLE/Email-LocalDelivery-Store-0.01.tar.gz)
- [ ] FLAT-Legacy-FA (E/ES/ESTRABD/FLAT-Legacy-FA.1.tgz)
- [ ] File-Searcher (A/AS/ASTUBBS/File-Searcher-0.92.tar.gz)
- [ ] Fraction (K/KE/KEVINA/Fraction-v.53b.tar.gz)
- [ ] GIFgraph_Map (R/RA/RA/GIFgraph_Map-1.02.tgz)
- [x] Games-Poker-TexasHold-em (S/SI/SIMON/Games-Poker-TexasHold-em-1.4.tar.gz)
- [ ] Geo-PostalCode (T/TJ/TJMATHER/Geo-PostalCode-0.07.tar.gz)
- [ ] Graph-Maker (B/BA/BATZ/Graph-Maker-0.02.zip)
- [ ] HTML-QuickCheck (Y/YL/YLU/HTML-QuickCheck-1.0b1.tar.gz)
- [ ] IO-Async-Loop-AnyEvent2-ElectricBoogaloo (M/MA/MAUKE/IO-Async-Loop-AnyEvent2-ElectricBoogaloo-0.002.tar.gz)
- [ ] Lingua-JA-Numbers (D/DA/DANKOGAI/Lingua-JA-Numbers-0.04.tar.gz)
- [ ] Lingua-Word2Num (P/PE/PETAMEM/Lingua-Word2Num-0.0682.tar.gz)
- [ ] LoadWorm (G/GL/GLENNWOOD/LoadWorm-1.02.tar.gz)
- [ ] Math-Systems (W/WI/WILL/Math-Systems-0.01.tar.gz)
- [ ] Module-Install-AuthorTests (R/RJ/RJBS/Module-Install-AuthorTests-0.002.tar.gz)
- [ ] MooseX-Types-CPF (T/TB/TBR/MooseX-Types-CPF-0.02.tar.gz)
- [ ] Net-Rsh (A/AS/ASLETT/Net-Rsh-0.05.tar.gz)
- [ ] Net-SMS-O2_DE (P/PR/PROFANTER/Net-SMS-O2_DE-0.07.tar.gz)
- [ ] PDL-IO-NDF (T/TJ/TJENNESS/PDL-IO-NDF-1.04.tar.gz)
- [ ] Proc-PID-File-Fcntl (J/JG/JGMYERS/Proc-PID-File-Fcntl-1.01.tar.gz)
- [ ] QML-File (Z/ZB/ZBLAIR/QML-File-0.01.tar.gz)
- [ ] RTx-WebCronTool (A/AU/AUTRIJUS/RTx-WebCronTool-0.01.tar.gz)
- [ ] Siebel-Integration-Com (B/BO/BOYDLE/Siebel-Integration-Com-0.02.tar.gz)
- [ ] Sub-Called (R/RE/RENEEB/Sub-Called-0.03.tar.gz)
- [ ] Template-Plugin-Filter-I18N (I/ID/IDEN/Template-Plugin-Filter-I18N-0.01.tar.gz)
- [ ] Test-WriteVariants (T/TI/TIMB/Test-WriteVariants-0.007.tar.gz)
- [ ] Timestamp-Simple (S/SH/SHOOP/Timestamp-Simple-1.01.tar.gz)
- [ ] Types (S/SI/SIZUR/Types-0.1.tar.gz)
- [ ] VRML (H/HP/HPALM/VRML-1.10.tar.gz)
- [ ] WWW-Kinghost-Painel (E/ED/EDUARDOW/WWW-Kinghost-Painel-0.04.tar.gz)
- [ ] Win32_AdminMisc_Source (D/DA/DAVEROTH/Win32_AdminMisc_Source_980511.zip)
- [ ] Win32_Tie_Ini_Source (D/DA/DAVEROTH/Win32_Tie_Ini_Source_980311.zip)
- [ ] XML-Traverse-ParseTree (M/MB/MBUSIK/XML-Traverse-ParseTree-0.03.tar.gz)
- [ ] autoclass (C/CC/CCAVNOR/autoclass_v1_01.tgz)
- [ ] basis (S/SK/SKNPP/basis/basis-0.05003.tar.gz)
- [ ] c_plus_plus (I/IL/ILYAZ/modules/c_plus_plus-0.1.tar.gz)
- [ ] extensible_report_generator (P/PH/PHOENIXL/extensible_report_generator_1.13.zip)
- [ ] genomics (L/LT/LTBOOTS/test/genomics.01.tar.gz)
- [ ] ikiwiki-plugin-syntax (V/VM/VMORAL/ikiwiki-plugin-syntax_0.24.tar.gz)
- [ ] iodbc-wwwtools (B/BJ/BJEPS/iodbc-wwwtools-0.20b.zip)
- [ ] perlude (M/MA/MARCC/perlude-0.58.tar.gz)
- [ ] sofu-config (M/MA/MALUKU/sofu-config/sofu-config-0.5.tar.gz)
- [ ] uni-perl (M/MO/MONS/uni-perl-0.91.tar.gz)
- [ ] uplug-cs (T/TI/TIEDEMANN/uplug-cs-0.2.tar.gz)
- [ ] uplug-da (T/TI/TIEDEMANN/uplug-da-0.2.tar.gz)
- [ ] uplug-de (T/TI/TIEDEMANN/uplug-de-0.2.tar.gz)
- [ ] uplug-en (T/TI/TIEDEMANN/uplug-en-0.2.tar.gz)
- [ ] uplug-fr (T/TI/TIEDEMANN/uplug-fr-0.2.tar.gz)
- [ ] uplug-hu (T/TI/TIEDEMANN/uplug-hu-0.2.tar.gz)
- [ ] uplug-ru (T/TI/TIEDEMANN/uplug-ru-0.2.tar.gz)
- [ ] uplug-sl (T/TI/TIEDEMANN/uplug-sl-0.2.tar.gz)
- [ ] uplug-sv (T/TI/TIEDEMANN/uplug-sv-0.2.tar.gz)
- [ ] uplug-treetagger (T/TI/TIEDEMANN/uplug-treetagger-0.3.2.tar.gz)
- [ ] CGISession (J/JE/JEFF/CGISession.tar.gz)
- [ ] UDPServersAndClients (R/RO/ROBINBANK/UDPServersAndClients.zip)

**Comment by ranguard** [comment]
Xmas has gone.. and so it this ticket :)
