### ISSUE TITLE
[Meta/Policy] What is metacpan "for"

### ISSUE THREAD

**Issue by ribasushi** [CPAN-API/metacpan-web#1155]
This answer https://github.com/CPAN-API/metacpan-web/issues/1151#issuecomment-39844974 made me thinking: why does MetaCPAN have the odd policy of "if not in 02 - sucks to be you"?

One way to look at things is to say "MetaCPAN is a view into the currently indexed part of CPAN". This however has a number of inconsistencies:

* Users can (and very very often do) install stuff from CPAN that is *not* in the index. All current CPAN clients have support for at least one way of doing that, and cpanm has 3 distinct ways I can think of.

* Indexing rules change over time, thus making backpan search impractical (moving goalposts).

Thus it seems to me that search.cpan.org visibility rules are much more "logically correct" than the current hardline of 02-or-nothing.

Thoughts?

**Comment by ranguard** [comment]
Closing for now, can be re-opened when we can re-index what we have now and work out policies from there.
