### ISSUE TITLE
github-meets-cpan.com links not working

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#1162]
As you know http://github-meets-cpan.com is been shut down but the MetaCPAN profiles still link to it. I'd suggest those links should be removed from the profiles till the said site comes back. If at all.

(e.g. on my profile https://metacpan.org/author/SZABGAB grey/black heart)

**Comment by ranguard** [comment]
@oalders get it sorted man - so I can close this ticket!

**Comment by oalders** [comment]
It's on the master branch here: https://github.com/oalders/github-meets-cpan  95% ready.

**Comment by oalders** [comment]
Link now points to http://gh.metacpan.org/user/SZABGAB
