### ISSUE TITLE
search results for SVN::Web are not very helpful

### ISSUE THREAD

**Issue by rbo** [CPAN-API/metacpan-web#1163]
Hi,

the search result for SVN::Web are not very helpful. I can't find: https://metacpan.org/release/SVN-Web (Search string: SVN::Web)

And: @Cpan: http://search.cpan.org/~nikc/ SVN::Web is listed but not at metacpan: https://metacpan.org/author/NIKC

maybe it's because of: SVN::Web 0.63 is an unauthorizes  release (http://search.cpan.org/~djzort/SVN-Web-0.63/) 

Thanks
Robert

**Comment by ranguard** [comment]
Seems to be a permissions thing: 

https://metacpan.org/release/SVN-Web - lots of stuff is Unauthorised - this needs sorting out by a PAUSE admin... in pause
