### ISSUE TITLE
mcpan.org incorrect redirect

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#1227]
Currently http://search.mcpan.org/dist/Dancer/lib/Dancer/Cookbook.pod
redirects to https://metacpan.org/release/Dancer
instead of https://metacpan.org/pod/Dancer::Cookbook

Can this be fixed?

**Comment by oalders** [comment]
Now points at https://metacpan.org/pod/distribution/Dancer/lib/Dancer/Cookbook.pod
