### ISSUE TITLE
Activation email is sent to Pause's public account

### ISSUE THREAD

**Issue by OpossumPetya** [CPAN-API/metacpan-web#1250]
1. Logged in via Twitter account
2. Accessed Account -> Profile
3. Red color message on the page: "Error: In order to change your profile you have to connect your account to PAUSE."
4. Provided Pause ID: message said to activate via link in email, and that to *make sure I have forwarding set up correctly*.

In Pause account I have a public email address, and a secret one, and forwarding (from pauseid@cpan.org) is set to the secret address. This forwarding works, I tried it manually.
However, I have received activation email to my public email address.

Either message about forwarding in Pause account should be corrected, or email should be sent to the correct address.

**Comment by ranguard** [comment]
Unable to reproduce currently - could have been part of our issue when moving datacenters - closing for now
