### ISSUE TITLE
Search within a distribution returns duplicate hits

### ISSUE THREAD

**Issue by tsibley** [CPAN-API/metacpan-web#1253]
[Example](https://metacpan.org/search?q=dist%3ADBIx-Class+inflate) + screenshot:

![image](https://cloud.githubusercontent.com/assets/79913/3631634/246a2bca-0eb9-11e4-84a7-bff7d1748dbf.png)

In the screenshot, note that the first two results are the same, but they link to different urls!  The same is true for the last two results.

I suspect this is to do with the frontend merging searches for multiple document types, i.e. we find the module document based on the external .pod documentation, but we also find the file document of the external .pod itself.  This would account for the difference in links (first to the POD file, then to the package name).  Distribution-specific searches don't collapse search results, so this may be "works as intended", but it's counterintuitive.

**Comment by ranguard** [comment]
Relates to #1231
