### ISSUE TITLE
Notes and comments

### ISSUE THREAD

**Issue by harshals** [CPAN-API/metacpan-web#1259]
metacpan offers many options for single task. Which is great! But I keep forgetting which modules I had tried on earlier   and why it did not suite my purpose back then. I wish I can leave some personal comments/notes on each module . That will save lot of time instead of again trying out the same module and reaching the same conclusion. Again.

**Comment by ranguard** [comment]
Nice idea, but too many other issues to fix and not enough volunteers to help
