### ISSUE TITLE
please unhide the github link

### ISSUE THREAD

**Issue by wchristian** [CPAN-API/metacpan-web#1263]
Originally the metacpan github link was in a good position. The universally accepted top right corner where github links on web pages go.

It wasn't labeled "github link" but it was good enough.

Now i see it's been moved to the left, and is labeled feedback, which makes it hard to find it without actively searching for it (note the use of the word "searching", it is a very heavy word to use for a process that should optimally require zero cerebral activity on the user's side). In fact, when i look at it i half-expect a mail form.

Thus, i'd like to discuss here how this can be made prominent again.

I'd most prefer it being to the right of the account drop-down, simply labeled "Github Issues", though i expect some resistance, or would hope for alternative suggestions that are more pretty.

**Comment by ranguard** [comment]
The 'fork metacpan' is in the footer
