### ISSUE TITLE
Show boilerplate installation instructions for each module

### ISSUE THREAD

**Issue by nicklangridge** [CPAN-API/metacpan-web#1295]
To quote this article http://perltricks.com/article/110/2014/8/21/Who-has-the-best-package-manager--Part-one

"metacpan should provide installation instructions for every package, which would be easy boilerplate using the cpan command line tool"

I think this is a good suggestion. Possibly the user could choose between cpan or cpanm boilerplate.

**Comment by oalders** [comment]
This was implemented via #1484
