### ISSUE TITLE
Search for perlrun - first hit is probably not what you want

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#1373]
https://metacpan.org/search?q=perlrun&size=100

The first hit I get is to https://metacpan.org/pod/distribution/PodSimplify/newrun.pod which seems like a very old copy of the second hit which is the perlrun in the latest version of perl: https://metacpan.org/pod/distribution/perl/pod/perlrun.pod

As a generic solution, would it make sense to prioritize any hit in the core perl distribution higher than any hit elsewhere?

**Comment by ranguard** [comment]
Relates to: #1231
