### ISSUE TITLE
JavaScript script makes the source view of a module unresponsive in FIrefox

### ISSUE THREAD

**Issue by kberov** [CPAN-API/metacpan-web#1388]
Clicking on "Source" link in the left panel of a module takes quite long time and the tab hangs for a while in
Mozilla FIrefox.
Example: https://metacpan.org/source/CAPTTOFU/DBD-mysql-4.028/lib/DBD/mysql.pm
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:32.0) Gecko/20100101 Firefox/32.0
Sometimes An allert box appears saying:
![unresponsive-script-metacpan](https://cloud.githubusercontent.com/assets/111614/4607287/16a637a8-5249-11e4-92b9-572009ae4abf.png)

If I try to debug the script Firefox crashes.
Looking at the source file I see this is
```
 /* 
 * TableSorter 2.0 - Client-side table sorting with ease!
 * Version 2.0.5b
 * @requires jQuery v1.2.3
 * 
 * Copyright (c) 2007 Christian Bach
 * Examples and docs at: http://tablesorter.com
 * Dual licensed under the MIT and GPL licenses:
 * http://www.opensource.org/licenses/mit-license.php
 * http://www.gnu.org/licenses/gpl.html
 * 
 */
```

**Comment by ranguard** [comment]
Seems ok in FF now
