### ISSUE TITLE
Distribution name normalizations

### ISSUE THREAD

**Issue by schwern** [CPAN-API/metacpan-web#1394]
As part of Gitpan I examined all the distributions/releases which have the same name but different cases and normalized them.  I figure this information is useful to MetaCPAN.

I put them into these categories...

* Those which are the same distribution, but a mistake in a release.
* Those which are the same distribution, and a deliberate change of case.
* Those which are a different distribution.
* Those which are early releases of a distribution which has been renamed.

The data is in the [Gitpan config file](https://github.com/evalEmpire/gitpan/blob/master/.gitpan) and I can explain it in more detail if you're interested in using the information to improve MetaCPAN.

**Comment by ranguard** [comment]
as @oalders knows about this now, closing - thanks
