### ISSUE TITLE
Would you like to take over Gitpan?

### ISSUE THREAD

**Issue by schwern** [CPAN-API/metacpan-web#1395]
Hi,

Gitpan is a project of mine to import all of BackPAN into Github.  Each distribution gets its own repository, each release is a commit.  Since its initial prototype a number of years ago, I have rewritten Gitpan to be far more maintainable and modular and the re-import is almost complete.

I have no interest nor skill in maintaining production systems.  Gitpan and MetaCPAN have many overlapping goals.  Would MetaCPAN be interested in taking over production maintenance of Gitpan?

I would imagine this would entail...
* Running the importer as a service on MetaCPAN machines.
* Adapting the Gitpan code to use MetaCPAN as a source rather than BackPAN::Index.
* Adapting the Gitpan code to log according to MetaCPAN's needs.
* Handing over the necessary Github access bits to MetaCPAN.

Gitpan isn't that complicated and much of it is likely redundant with MetaCPAN.

[Here is the code](https://github.com/evalEmpire/gitpan/).
[Here is the result](https://github.com/gitpan).
As of this writing the import is about 60% complete and on hold pending a few fixups to the importer heuristics.

**Comment by schwern** [comment]
It looks like Gitpan would go somewhere in MetaCPAN::Script::Release->import_tarball, but where?  It's a big method that could use some extraction.  My impulse is to put it just before `$tmpdir->rmtree;` at the end.

$release and $tmpdir have almost everything Gitpan::Release needs.  I need the author's name and email address as well.

**Comment by oalders** [comment]
That method can use some refactoring. @andreeap is working on that today, actually.  Just before $tmpdir->rmtree works for me.  

We should add a flag to enable Gitpan in this script.  It will, most likely, be running on more than one machine once we get more redundancy, so we'll only want to do this on one production machine.  It should be off by default is best since we run this script a lot at the command line to re-index releases.

I guess we can wrap this with Try::Tiny to ensure that a failure doesn't take down the indexer?

**Comment by andreeap** [comment]
I could help with this.

**Comment by schwern** [comment]
@andreeap Thanks for the offer.  I'll definitely take you up on that
once I get metacpan-developer working.

Is there a way I can run the importer without the full vagrant/vitualbox
setup?

**Comment by schwern** [comment]
Nevermind, I got it working and the metacpan-api tests are running. Using VirtualBox  4.3.10 appears to be a requirement, not a recommendation.

How should I go about unit testing import_tarball?

**Comment by oalders** [comment]
You don't have to use VirtualBox, but it can be quite painful to set things up yourself and then keep up with any changes.  

There's no test that deals with just the import_tarball method, so it would probably be a good idea to add one and start from there.  If we get your changes in before @andreeap's then she'll just sort out the merge conflicts.

**Comment by schwern** [comment]
How about I help @andreeap with the refactoring, get to know the code, improve the tests, and once that's done I'll work on integrating Gitpan?  Andreea, want some help?

**Comment by oalders** [comment]
You, sir, have read my mind.  That sounds like the perfect plan to me.  Andreea has been doing some pair programming, so that might be an option to move forward with this.

**Comment by andreeap** [comment]
Yes, of course, that will be great. I am on #metacpan so we can talk on details.

**Comment by schwern** [comment]
I'm ready to start hooking in Gitpan!  I'm going to close this and open issues in the cpan-api repository.
