### ISSUE TITLE
Process TODO contents as markdown and display on distribution's home page

### ISSUE THREAD

**Issue by neilbowers** [CPAN-API/metacpan-web#1426]
If a distribution contains a TODO file, how about displaying it's contents in the distribution's home page, the same way an extract of Changes is displayed?

Assume the file is markdown, and if that fails, display it in a preformatted block. I reckon most people/distributions will just want a simple ASCII bulleted list. People can split it into multiple lists with markdown headers, if they have such complex todo list needs (yeah, I'm looking at you @ribasushi! ;-)

This might encourage people to share their ideas for their dist's evolution, and would be helpful for the various pull request challenges.

**Comment by ranguard** [comment]
Closing as no one has stepped forward to do it
