### ISSUE TITLE
Showing the README.pod as module documentation is confusing

### ISSUE THREAD

**Issue by robrwo** [CPAN-API/metacpan-web#1428]
Some of my modules (author rrwo, such as [Pod-Readme](https://metacpan.org/release/Pod-Readme) or MooX-Failover) have README.pod instead of plain text README files. But MetaCPAN shows the README as the module documentation.

This seems to confuse people looking at a module. I've gotten comments from somebody wondering why the extraneous stuff about installation/requirements was in the POD but not a full description.

**Comment by ranguard** [comment]
Probably fixed with https://github.com/CPAN-API/metacpan-web/pull/1463
