### ISSUE TITLE
class "hidden-xs" is preventing normal usage

### ISSUE THREAD

**Issue by andk** [CPAN-API/metacpan-web#1429]
![Uploading metacpan-html-bug.png . . .]()

In the attached image firebug highlights how a div element of the class "hidden-xs" is covering the links "Switch" and "Test::More" on the page /release/Net-PJLink. On that page I could click on IO::Select but not on Switch or Test::More. The links were visible and their color was indicating that these were links but a click was without consequences.

**Comment by ranguard** [comment]
Unable to produce - assuming fixed by something else
