### ISSUE TITLE
Negative number of non-PAUSE ++ers

### ISSUE THREAD

**Issue by choroba** [CPAN-API/metacpan-web#1430]
See also https://github.com/CPAN-API/metacpan-web/issues/1305
This time at [JSON::Parse](http://metacpan.org/pod/JSON::Parse)
![1](https://cloud.githubusercontent.com/assets/886196/5468522/751d7cf0-85d0-11e4-8bd0-eee72dc2d073.png)

**Comment by oalders** [comment]
Math is hard.

![screenshot 2015-01-17 07 11 48](https://cloud.githubusercontent.com/assets/96205/5788780/35b77916-9e18-11e4-8bc6-61ca1b0322ed.png)

This highlights the fact that we need to be using the same logic to calculate the ++ in the badge.

**Comment by Csson** [comment]
Every distribution I have seen that on has been ++ by both sharyanto and perlancar. Maybe that helps tracking it down.

**Comment by oalders** [comment]
Looks like this was fixed via #1455.  Thanks @oiami :)
