### ISSUE TITLE
Can't add PAUSE account to my identities

### ISSUE THREAD

**Issue by reneeb** [CPAN-API/metacpan-web#1431]
When I try to add my PAUSE account (RENEEB) to my identities, I see the page that an email is sent. But I never get this email (spam folder was double checked). The email setup of my PAUSE account works.

Maybe this is caused by the wrong email adress that is shown nn my MetaCPAN authors page. module@renee-baecker.de doesn't work.

**Comment by ranguard** [comment]
@reneeb please try again and comment here - will re-open the issue if you still have problems

**Comment by reneeb** [comment]
It won't work until the mail address is updated... It may be not an issue of metacpan-web, but of MetaCPAN/Script/Author.pm in cpan-api. I have no clue why the old address is still on MetaCPAN. It doesn't appear anywhere in PAUSE since some months...

And the correct address is in http://www.cpan.org/authors/00whois.xml

**Comment by oalders** [comment]
> host mx02.mail-redirect.eu[159.69.107.183] said: 554
>    5.7.1 <[[REDACTED]]>: Relay access denied (in reply to RCPT TO
>    command)

**Comment by oalders** [comment]
Gmail doesn't want to deliver to this address either:

> ** Message not delivered **
> Your message couldn't be delivered to [REDACTED] because the remote server is misconfigured. See the  technical details below for more information.
> The response from the remote server was:
554 5.7.1 <[REDACTED]>: Relay access denied

**Comment by reneeb** [comment]
Can you try reneeb@cpan.org?

**Comment by oalders** [comment]
Sent

**Comment by reneeb** [comment]
Thanks, I got the mail. When I click on the link, I get this response:

![image](https://user-images.githubusercontent.com/144096/163240026-8e3cfec5-bdac-4d42-b8bf-db360b84053e.png)

And the PAUSE account is still not added to my identities:

![image](https://user-images.githubusercontent.com/144096/163240193-5d55b5f4-1765-4332-ac05-a37db3dab71b.png)

**Comment by oalders** [comment]
Could you trigger a new code and I send it to you again?

**Comment by reneeb** [comment]
Done...

**Comment by oalders** [comment]
Oof. @reneeb did this actually ever get resolved?
