### ISSUE TITLE
Complete::Module 0.13 is not indexed

### ISSUE THREAD

**Issue by perlancar** [CPAN-API/metacpan-web#1436]
It is on search.cpan.org: http://search.cpan.org/~perlancar/Complete-Module-0.13/

and it's not UNAUTHORIZED in search.cpan.org.

**Comment by rwstauner** [comment]
It is indexed, however it does not show up in listings because it isn't in
02packages

https://metacpan.org/release/PERLANCAR/Complete-Module-0.13
