### ISSUE TITLE
Complete::Dist::Zilla not indexed

### ISSUE THREAD

**Issue by perlancar** [CPAN-API/metacpan-web#1437]
it's indexed by search.cpan.org (and not UNAUTHORIZED)

http://search.cpan.org/~perlancar/Complete-Dist-Zilla-0.02/

**Comment by rwstauner** [comment]
It is indexed, however it does not show up in listings because it isn't in
02packages

https://metacpan.org/release/PERLANCAR/Complete-Dist-Zilla-0.02
