### ISSUE TITLE
Index the core perl functions

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#1440]
It would be nice if I typed ```print``` in the search box, the first hit was to https://metacpan.org/pod/distribution/perl/pod/perlfunc.pod#print

**Comment by rwstauner** [comment]
It would be nice to score those higher.

I'm not sure where the authoritative info for that would come from, but
it's something to look into.

**Comment by ranguard** [comment]
This should be in the API not UI
