### ISSUE TITLE
Exact anchor at the top

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#1442]
Some core perl functions have multiple anchors for example:
https://metacpan.org/pod/distribution/perl/pod/perlfunc.pod#caller
https://metacpan.org/pod/distribution/perl/pod/perlfunc.pod#caller-EXPR

IMHO it would be better to put the exact anchor (#caller in this case) to the top so if someone links to that anchor the others are visible.

**Comment by rwstauner** [comment]
I don't understand.   What do you mean by "put the anchor to the top"?

**Comment by szabgab** [comment]
I mean that the link leading to #caller (In the above example) will be the top-most of all the #caller-... links. If you click on that link now the usage example ```caller EXPR``` is not shown.

**Comment by rwstauner** [comment]
Ah, I see: The "caller" function has a heading for each usage example.

To me it seems like that request should be made to the perl core to switch
the order of the directives in the pod.

**Comment by haarg** [comment]
There's a partly related thing here. Ideally, all of the functions would be linkable with L<perlfunc/caller> or similar, but that currently isn't the case.  Not all functions have a bare form with no arguments.  That isn't something that could be fixed by reordering.

**Comment by rwstauner** [comment]
We can create anchors based on `X<>` codes, but there are duplicates (since they are also used for indexing) so that doesn't help entirely either.

**Comment by ranguard** [comment]
Unable to resolve currently
