### ISSUE TITLE
FCGI::ProcManager page missing

### ISSUE THREAD

**Issue by davewood** [CPAN-API/metacpan-web#1443]
When I visit https://metacpan.org/pod/FCGI::ProcManager (a spage i viewed successfully in the past) I get "Error 404 Not Found"

the module is listed in https://cpan.metacpan.org/modules/02packages.details.txt

FCGI::ProcManager                  0.25  A/AR/ARODLAND/FCGI-ProcManager-0.25.tar.gz

$ cpanm FCGI::ProcManager
--> Working on FCGI::ProcManager
Fetching http://www.cpan.org/authors/id/A/AR/ARODLAND/FCGI-ProcManager-0.25.tar.gz ... OK
Configuring FCGI-ProcManager-0.25 ... OK
Building and testing FCGI-ProcManager-0.25 ... OK
Successfully installed FCGI-ProcManager-0.25 (upgraded from 0.24)
1 distribution installed

$ cpanm info FCGI::ProcManager
! Finding info on cpanmetadb failed.
! Finding info () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution info
FCGI::ProcManager is up to date. (0.25)

**Comment by wchristian** [comment]
Same module on sco: http://search.cpan.org/~arodland/FCGI-ProcManager-0.25/

**Comment by rwstauner** [comment]
Fixed by reindexing.
Thanks for reporting.
