### ISSUE TITLE
Make linkified URLs in comments in source view underlined

### ISSUE THREAD

**Issue by bpj** [CPAN-API/metacpan-web#1445]
# Make linkified URLs in comments in source view underlined

(Sorry about hitting send too early before. My tablet suddenly zoomed for some reason.)

Please make linkified URLs in source view underlined. I just discovered they *were* links after 3 years or so. Underlining them might help the next guy!

**Comment by rwstauner** [comment]
Can you provide an example?

**Comment by plu** [comment]
![pod_links](https://cloud.githubusercontent.com/assets/31597/7219629/d1d01366-e6a8-11e4-8b06-ba920f0584dd.png)
![pod_links_underlined](https://cloud.githubusercontent.com/assets/31597/7219630/d4f3a86e-e6a8-11e4-8a36-3f9b05088c57.png)

Something like this, right?
