### ISSUE TITLE
LWP::UserAgent::Determined Missing

### ISSUE THREAD

**Issue by ctriv** [CPAN-API/metacpan-web#1446]
LWP::UserAgent::Determined shows up on search.cpan (http://search.cpan.org/~alexmv/LWP-UserAgent-Determined-1.07/lib/LWP/UserAgent/Determined.pm) but not on metacpan.

    $ curl http://api.metacpan.org/v0/module/LWP::UserAgent::Determined
    {
       "message" : "Not found",
       "code" : 404
    }

**Comment by rwstauner** [comment]
A reindex fixed it... The module was listed as "unauthorized" last time.
Thanks for reporting!
