### ISSUE TITLE
Incorrect number of RT issues

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#1447]
https://metacpan.org/pod/Term::ProgressBar tells me there is 1 Issue but if I click through to RT there are two: a 3-year old issue in 'open' status and 13 days old issue in 'new' status.

**Comment by rwstauner** [comment]
This is fixed.  @haarg ++

**Comment by haarg** [comment]
For reference, this was CPAN-API/cpan-api#382

**Comment by szabgab** [comment]
:cool:
