### ISSUE TITLE
Error message when hovering over the 'Clone repository' link for Text-Textile

### ISSUE THREAD

**Issue by neilbowers** [CPAN-API/metacpan-web#1449]
hovering over the "Clone repository" link for [Text-Textile](https://metacpan.org/pod/Text::Textile) results in the following error message:

    parsererror:SyntaxError: JSON Parse error: Unrecognized token '<'

I didn't get it on the next distribution I tried.

Text-Textile has a non-standard repo in the metadata, dunno if that's the issue:

    http://github.com/bradchoate/text-textile/tree/master

**Comment by rwstauner** [comment]
Likely... I recently allowed for the trailing "/tree" but the extra
"master" is probably returning a 404

**Comment by rwstauner** [comment]
Fixed. Thanks for reporting!
