### ISSUE TITLE
The site is currently broken

### ISSUE THREAD

**Issue by pwr22** [CPAN-API/metacpan-web#1453]
Using search terms that earlier returned results now no longer return anything. All pages seem to return not found

Example: https://metacpan.org/release/POE-Component-Server-Twirc

**Comment by jmacdotorg** [comment]
I can confirm this observation.

**Comment by oalders** [comment]
Elasticsearch had stopped. I've restarted it and looks OK now.  Ping me here if it isn't.  Thanks very much for reporting!
