### ISSUE TITLE
Issue when searching for modules - no results returned

### ISSUE THREAD

**Issue by atcroft** [CPAN-API/metacpan-web#1454]
Another user on the PerlMonks website asked if something was wrong with metaCPAN. When I tested for myself, I found that no results were being returned for any module I entered. Examples searched for included Archive::Tar, Test::Simple, and Task::Kensho.

When looking through the site to try to determine what may be occurring, I found the following error message in the "Indexer Log" page from the "Recent" link:

Level: error
Script: watcher
Message: getting latest release failed: [ERROR] ** ElasticSearch::Error::NoServers at /home/metacpan/carton/metacpan-api/lib/perl5/ElasticSearch/Transport.pm line 268 : Could not retrieve a list of active servers: [ERROR] ** ElasticSearch::Error::Connection at /home/metacpan/carton/metacpan-api/lib/perl5/ElasticSearch/Transport/HTTPTiny.pm line 75 : Could not connect to '127.0.0.1:9200': IO::Socket::INET: connect: Connection refused (599) With vars:{ 'request' => { 'method' => 'GET', 'cmd' => '/_cluster/nodes', 'qs' => { 'http' => 1 } }, 'status_code' => 599, 'status_msg' => 'Could not connect to \'127.0.0.1:9200\': IO::Socket::INET: connect: Connection refused ', 'server' => '127.0.0.1:9200' } With vars:{ 'servers' => [ '127.0.0.1:9200' ] }
Date: a minute ago

**Comment by mauke** [comment]
Looks like it's working again.

**Comment by oalders** [comment]
@ranguard restarted Elasticsearch for us.  Not sure what this issue is. Thanks for reporting!
