### ISSUE TITLE
Automatically re-index releases if they change in 02packages.details.txt

### ISSUE THREAD

**Issue by neilbowers** [CPAN-API/metacpan-web#1456]
MetaCPAN could identify when a release needs indexing by comparing that release's details in two different versions of 02packages. Here's a quick outline of how I think it could work.

When importing a new drop of 02packages, iterate over all releases

 * build a list of all [module,version] seen in the release
 * sort that list by module name
 * create a 'signature' for the release, by concatenating them into a string
 * if there was an entry for that release in the previous version of 02packages, compare signatures.
 * if the signature has changed, then the release has been re-indexed by PAUSE, so MetaCPAN knows to re-index.

This should be called the HAARGOMATIC, since in a discussion in #metacpan, @haarg pointed out that the need for re-indexing could be identified off sequential drops of 02packages.

**Comment by oalders** [comment]
@neilbowers Why was this closed?

**Comment by neilbowers** [comment]
I realised I should have put it on cpan-api, so I closed it here and added it there.

**Comment by oalders** [comment]
OK. :) https://github.com/CPAN-API/cpan-api/issues/390
