### ISSUE TITLE
cPanel::SyncUtil 0.8 not listed on metacpan

### ISSUE THREAD

**Issue by toddr** [CPAN-API/metacpan-web#1470]
I uploaded cPanel::SyncUtil 0.8 as the pause user CPANEL 7 hours ago and it still is not showing up on metacpan. It is listed in 02packages.details.txt.gz and CPANEL has co-maint on this module. Can
you advise why it's not listed?

**Comment by oalders** [comment]
It's there now after a manual re-index.
