### ISSUE TITLE
The "Module Documentation" link on the Source page can be wrong

### ISSUE THREAD

**Issue by rwstauner** [CPAN-API/metacpan-web#1472]
Viewing the source of a pod file...
if that file has a `=head1 NAME` (and therefore a `"file.documentation"`)
it gets a "Module Documentation" link instead of a "Documentation View" link.
However the "Module Documentation" link (`/pod/Foo`) should be limited to indexed (02packages)/authorized/latest modules (as that's all the `/pod/Foo` link is intended for).

For example: [a changelog](https://metacpan.org/source/RURBAN/Set-Object-1.34/Changes.pod) should link to `/pod/author/release/path...` rather than `/pod/REVISION`.

I attempted to change

`<% IF module.documentation %>`
to
```
  <% IF module.documentation && module.status == "latest" && module.module &&
        module.module.grep(->(m){ m.authorized && m.indexed && m.name == module.documentation }) %>
```
in the view.
However that fails for modules that have `.pod` separate from `.pm` (`Pod::Simple`, for example).

So, in order to be accurate, I think what we need here is to additionally get the file that has the package matching `file.documentation`, and check if that `"module"` is authorized, indexed, and has `"associated_pod"` matching the pod file that we started with (the Source view).

Anyone have a better idea?

**Comment by rwstauner** [comment]
Maybe what we should be doing is back-linking the pod to the module.
Currently we link a module to it's pod (`"associated_pod"`) so that from a module you know how to display it's pod.  Perhaps we should also have that link in the other direction so that from a pod file you know which module it's for.

I suppose that's what `"file.documentation"` is supposed to mean, but obviously it's frequently wrong (or at least unhelpful).  Knowing the path to the appropriate file would make it easy to check if that file is indexed/authorized/latest, etc.

**Comment by ranguard** [comment]
These seem to be @rwstauner's own thoughts and we've not followed up, so closing for now
