### ISSUE TITLE
[wishlist] Simple improvement to the changelog parser

### ISSUE THREAD

**Issue by ribasushi** [CPAN-API/metacpan-web#1474]
Am filing this from IRC, so it won't get lost:

Idle thought - linkifying any URIs found in the changelog would probably be handy: https://metacpan.org/release/RIBASUSHI/DBIx-Class-0.082819_01#whatsnew

**Comment by ribasushi** [comment]
While browsing stuff with @oalders I noticed that the [**actual** changelog](https://metacpan.org/source/RIBASUSHI/DBIx-Class-0.082820/Changes) in fact got linkified, but the part I was talking about ([the partial log in the main page](https://metacpan.org/release/RIBASUSHI/DBIx-Class-0.082820#whatsnew)) still isn't linked through correctly.

Cheers

**Comment by haarg** [comment]
The linking in the full change log is handled by the client side syntax highlighter. The change log snippet is done server side as part of generating the release page. So there are a number of differences in how things are linked.

**Comment by ranguard** [comment]
No action has happened, do add to the wishlist if you want it still listed as something that could be worked on
