### ISSUE TITLE
No issues for PAR

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#1477]
https://metacpan.org/pod/PAR does not show the number of issues, but if I click through to RT, there are a few.

**Comment by ranguard** [comment]
Probably relates to https://github.com/CPAN-API/metacpan-web/pull/1475 - I'll try look next week if no one beats me to it

**Comment by oalders** [comment]
I see 22 issues now.  I'm guessing @ranguard fixed this. :)
