### ISSUE TITLE
Makefile.PL is recognized as documentation.

### ISSUE THREAD

**Issue by van-de-bugger** [CPAN-API/metacpan-web#1478]
In my `Makefile.PL` there is a comment like this:

    =comment
    ...
    =cut

MetaCPAN (wrongly) recognizes Makefile.PL as documentation file, see https://metacpan.org/release/VDB/Systemd-Daemon-0.01, while search.span.org does not.

This issue is similar to bug #460, and, I guess, can be workarounded by including Makefile.PL to `no_index`. However, this is a workaround, not a solution. I believe MetaCPAN should not treat common boilerplate files (such as Makefile.PL, Build.PL, etc) as documentation.

**Comment by rwstauner** [comment]
This was a bug in the indexer and has been fixed.
Thanks for reporting.
