### ISSUE TITLE
Override pod hiding when opening a page with a linked line number

### ISSUE THREAD

**Issue by oalders** [CPAN-API/metacpan-web#1480]
I just went to this page and got really confused: https://metacpan.org/source/OALDERS/Module-Version-Loaded-0.000003/lib/Module/Version/Loaded.pm#L84

I had my "display pod" toggled to off, so it naturally didn't show me anything useful.  This seems like a case where we could force the Pod to be displayed.

**Comment by haarg** [comment]
Fixed by bcedc25af4d0e28350da04db6d657bd4a2525a74
