### ISSUE TITLE
README.pod isn't shown anymore

### ISSUE THREAD

**Issue by nwellnhof** [CPAN-API/metacpan-web#1482]
Commit https://github.com/CPAN-API/metacpan-web/commit/84bfc779a2529837800d4b8dace9fe781b20ba2a disables the display of `README.pod` files. I don't agree with the rationale. `README.pod` files are the only way to show rich text readme files on both GitHub and MetaCPAN. Their installation can be prevented by listing `README` in `INSTALL.SKIP`.

**Comment by ranguard** [comment]
@nwellnhof others seem to have the opposite view... https://github.com/CPAN-API/metacpan-web/issues/1428 and have had to work around it https://github.com/CPAN-API/metacpan-web/issues/460

@karenetheridge care to comment?

**Comment by nwellnhof** [comment]
Well, #460 and #1428 are not about hiding `README.pod`. Both issues were opened by users who obviously like to have a `README.pod` in their module and who would probably be opposed to completely hiding it on MetaCPAN. I'm aware that there are some difficulties handling these POD files but I don't think hiding them does users a favor. I didn't have a problem with the way MetaCPAN handled the files before.

@karenetheridge made a different point. AFAIU, she considers `README.pod`s bad practice in general and therefore, MetaCPAN should discourage their use. I disagree with this view. I prefer a `README.pod` over a `README.md` because MetaCPAN and GitHub are able to render them nicely. The installation issues can be worked around easily. I don't think that I'm alone with this opinion and that it's basically a matter of personal preference. As long as there aren't any serious technical problems, the choice should be up to the module authors.

**Comment by karenetheridge** [comment]
> The installation issues can be worked around easily.

This hasn't been borne out by reality so far, unfortunately.

> Their installation can be prevented by listing README in INSTALL.SKIP.

This doesn't prevent manpages from being installed.  I suspect there are other toolchain issues as well, because .pod files are treated as significant by much of the toolchain.

I prefer pod over markdown as well. I use README.pod files in my github repositories (that contains the pod from the main module), but never package the file for distribution.

I don't see any gain in having a README.pod on metacpan, if it's just going to contain the same content as the main module.

question for @ranguard: is there anything that can be put *inside* a README file to indicate how it should be rendered?

**Comment by nwellnhof** [comment]
> This doesn't prevent manpages from being installed.

It does for me. At least on Ubuntu 14.10, stock Perl 5.20.1, EU::MM 6.98. (You have to make sure to only put `README` in `INSTALL.SKIP`, not `README.pod`.)

> I don't see any gain in having a README.pod on metacpan, if it's just going to contain the same content as the main module.

I use `README.pod` for installation instructions, so the content is different from the main module's POD.

**Comment by oalders** [comment]
Maybe we should get a few more people to chime in on this.  I don't have a strong opinion on how to handle this.

**Comment by karenetheridge** [comment]
I was thinking of raising it at Berlin, in the context of .pod files in general being treated weirdly (subjective!) by PAUSE and the toolchain.

**Comment by oalders** [comment]
@karenetheridge did this get raised in Berlin?

**Comment by nwellnhof** [comment]
Original issue that prompted the blacklisting: #1463

**Comment by ranguard** [comment]
@karenetheridge any update on this? or should we close for now?

**Comment by karenetheridge** [comment]
No updates from me.  I suppose we could alter metacpan to display README.pod if it was contained in INSTALL.SKIP, but just displaying it by default would continue to encourage its improper inclusion in distributions *without* the INSTALL.SKIP entry (its existence is not widely known).

**Comment by ranguard** [comment]
@nwellnhof would you care to submit a patch based on @karenetheridge's recommendation?

I'm labeling this volunteer needed for now

**Comment by nwellnhof** [comment]
On 08/03/2016 20:50, Leo Lapworth wrote:

> @nwellnhof <https://github.com/nwellnhof> would you care to submit a patch
> based on @karenetheridge <https://github.com/karenetheridge>'s recommendation?

No, I don't care that much about this issue.
