### ISSUE TITLE
Need to use https instead of http at /feed/recent

### ISSUE THREAD

**Issue by bessarabov** [CPAN-API/metacpan-web#1488]
Here a a line from https://metacpan.org/feed/recent:

```
<rdf:li rdf:resource="http://metacpan.org/release/SMUELLER/Math-Histogram-1.04" />
```

The scheme is http, but when you open this link you will be redirected to https. I think that it is better to use https scheme to speed up the work with link and to secure connection.

This resourse is used by twitter account that publishes info about new & updated modules — https://twitter.com/cpan_new So then this issue is resolved that twitter account will also be posting https links.

I've tried to solve this issue myself, I've found lib/MetaCPAN/Web/Controller/Feed.pm with 

```
sub recent : Chained('index') PathPart Args(0) {
    my ( $self, $c ) = @_;
   $c->forward('/recent/index');
    my $data = $c->stash;
    $c->stash->{feed} = $self->build_feed(
        title   => 'Recent CPAN uploads - MetaCPAN',
        entries => $data->{recent}
    );
}
``` 

But I don't understand what is `stash` and how I should change its content. So I've created this ticket.

**Comment by oalders** [comment]
Thanks for reporting. :+1:  It looks like there are 3 instances of 'http://' in `lib/MetaCPAN/Web/Controller/Feed.pm` that should be switched out.  However, building these urls with `$c->uri_for` would be the better solution in the long term.

BTW, the `stash` is basically a container of data which makes it convenient to pass data around.  If you put data in the `stash` then it will also be available to the templates when it's time to render them.

**Comment by bessarabov** [comment]
I used the simple solution. I thought about using `$c->uri_for`, but there was no `$c` in `build_entry()` I didn't wanted to pass it through several subs, so I this this simple change.

**Comment by bessarabov** [comment]
The solution for this ticket is merged, so I'm closing this issue.

**Comment by oalders** [comment]
@bessarabov Yep, that'll do for today.  We can do a more invasive change down the line.  Thanks for the  fix!
