### ISSUE TITLE
sidebar teleports out of screen while scrolling.

### ISSUE THREAD

**Issue by kentfredric** [CPAN-API/metacpan-web#1493]
Easiest viewed on imgur and compared by tapping left/right on keyboard.

http://imgur.com/a/XcNxA 

Yellow box indicates effective viewport at 2 conditions.

![Before](http://i.imgur.com/63YIIq0.png)
![After](http://i.imgur.com/IM7MTDG.png)

**Comment by haarg** [comment]
This is because the sidebar scrolling code isn't accounting for the right sidebar being longer than the content.
