### ISSUE TITLE
Add <link rel=alternate> tags pointing to the API query

### ISSUE THREAD

**Issue by dolmen** [CPAN-API/metacpan-web#1494]
To help discover the API, it would be helpful to provide in the HTML source of each page of MetaCPAN.org an alternate link pointing to the API query that returns the data that has been used to generate the page content.

For example, on [/author/DOLMEN](https://metacpan.org/author/DOLMEN) I would like:
```
<link rel="alternate" type="application/json" href="//api.metacpan.org/v0/author/DOLMEN">
```

This kind of information would be much more useful on pages such as [/requires/distribution/Time-Piece](https://metacpan.org/requires/distribution/Time-Piece) that seem to be complex to build for an API beginner.

**Comment by rwstauner** [comment]
Interesting idea, but would definitely need some thought on a per page
basis.
Many pages involve more than one query, and a lot of post-processing.
Something to think about though, and doing so might help us make the API
better.

**Comment by oalders** [comment]
@dolmen we do have the "MetaCPAN Explorer" link on the bottom left of the page.  Does this get you at least part of the way there?

**Comment by oalders** [comment]
@dolmen ^^^

**Comment by dolmen** [comment]
Yes, the MetaCPAN Explorer link is very helpful for humans.
The alternate link with JSON data would be helpful for machines, but I admit I have no real use case for that.
So this request can be closed.

**Comment by oalders** [comment]
@dolmen thanks for the followup. :)
