### ISSUE TITLE
[UI] Missing navigation within the diff interface

### ISSUE THREAD

**Issue by ribasushi** [CPAN-API/metacpan-web#1500]
Here is how a usual debugging session goes:
...
1. Go to metacpan find [module within dist in question](https://metacpan.org/pod/release/RIBASUSHI/DBIx-Class-0.082820/lib/DBIx/Class.pod) 
2. Realize something changed strangely, go to the bottom left, ask for a [diff with a previous version](https://metacpan.org/diff/file?target=RIBASUSHI/DBIx-Class-0.082820/lib/DBIx/Class.pod&source=RIBASUSHI/DBIx-Class-0.082810/lib/DBIx/Class.pod)
3. Realize this shows me only one-file diff, curse, [go back to the pod-page](https://metacpan.org/pod/release/RIBASUSHI/DBIx-Class-0.082820/lib/DBIx/Class.pod)
4. Go to [the dist-view](https://metacpan.org/release/RIBASUSHI/DBIx-Class-0.082820) (click on top)
5. Go to diff on the bottom right again, see [what I wanted to see at point 3](https://metacpan.org/diff/file?target=RIBASUSHI/DBIx-Class-0.082820/&source=RIBASUSHI/DBIx-Class-0.082810/)

It would be awesome if the "single file diff" had a "get full dist diff" link, so one can jump from point 2 to point 5 directly

**Comment by oalders** [comment]
We could add this link near the "This is a file diff" message.  We would only need to show it for file diffs.
