### ISSUE TITLE
Pod name repeats itself

### ISSUE THREAD

**Issue by oalders** [CPAN-API/metacpan-web#1506]
https://metacpan.org/release/Math-Algebra-Symbols

![screenshot 2015-04-19 17 39 28](https://cloud.githubusercontent.com/assets/96205/7220060/13926238-e6bb-11e4-9c10-ba740011efad.png)

This was pointed out by @rjbs.  I could have sworn @ribasushi pointed this out earlier this week, but I can't find the relevant ticket.

**Comment by oalders** [comment]
The relevant issue is #1509

**Comment by ranguard** [comment]
Closing as related to #1509
