### ISSUE TITLE
[UI] [Wishlist] Bubble up the "#whatsnew" heading 

### ISSUE THREAD

**Issue by ribasushi** [CPAN-API/metacpan-web#1510]
The "changes since last version" is getting buried deep down, as many popular distributions are rather large. Some examples:

https://metacpan.org/release/Moose
https://metacpan.org/release/Catalyst-Runtime
https://metacpan.org/release/DBIx-Class

All three of the above would benefit from the `#whatsnew` heading being placed first, before `Documentation`

**Comment by oalders** [comment]
I'm fine with placing this first.  Any other opinions?

**Comment by haarg** [comment]
+1

**Comment by ribasushi** [comment]
Bump?
