### ISSUE TITLE
[UI] [Wishlist] Link files mentioned in the changelog delta to their source-listing from the same tarball

### ISSUE THREAD

**Issue by ribasushi** [CPAN-API/metacpan-web#1511]
The [delta for DBIC 0.082820](https://metacpan.org/release/RIBASUSHI/DBIx-Class-0.082820#whatsnew) mentions `t/72pg.t` and `t/54taint.t`. It would be neat if they linked to [t/72pg.t](https://metacpan.org/source/RIBASUSHI/DBIx-Class-0.082820/t/72pg.t) and [t/54taint.t](https://metacpan.org/source/RIBASUSHI/DBIx-Class-0.082820/t/54taint.t) respectively. Ticket relates to https://github.com/CPAN-API/metacpan-web/issues/1474

Cheers

**Comment by ranguard** [comment]
Moved to wishlist
