### ISSUE TITLE
Add a redirect permalink pointing to the web of the repository

### ISSUE THREAD

**Issue by dolmen** [CPAN-API/metacpan-web#1512]
Add an URL that would redirect (temporary, 302) to the WWW of the repository ([`resources/repository/web` in META v2](https://metacpan.org/pod/CPAN::Meta::Spec#resources)).

I propose `/repository/<dist name>`

Use case:
> Google Code is closing. So I'm moving my repos to Github and I want to link from the old Google Code project to the new one. But instead of hard linking to Github, I would prefer to have a kind of symlink on metacpan.org that would then redirect to whatever is the repo address (as specified in META of the latest release) at the time of the request.

**Comment by oalders** [comment]
I think this is a great idea.  Shouldn't be difficult to implement.

**Comment by dolmen** [comment]
Well, it's too late for my Google Code use case: Google Code is now readonly, so I can not modify the home page of the project. :(

But the feature would still be useful for other use cases!

**Comment by ranguard** [comment]
I've added this to the wishlist https://github.com/CPAN-API/cpan-api/wiki/Wishlist#misc
