### ISSUE TITLE
"API" link in footer points to an obsolete link

### ISSUE THREAD

**Issue by dolmen** [CPAN-API/metacpan-web#1513]
In the footer of every MetaCPAN.org page, the "API" word links to https://github.com/CPAN-API/cpan-api/wiki/API-docs
However that page says:
> Note: Under Construction
> The contents of this page have been moved [into the repo](https://github.com/CPAN-API/cpan-api/blob/master/docs/API-docs.md)

So, the link should point instead directly to the current location.

**Comment by dolmen** [comment]
Same issue on MetaCPAN Explorer for the link "API documentation" in the sidebar.

**Comment by rwstauner** [comment]
Thanks for reporting!
