### ISSUE TITLE
Syntax highlight broken on source files

### ISSUE THREAD

**Issue by oalders** [CPAN-API/metacpan-web#1516]
For example: https://metacpan.org/source/BDFOY/Crypt-Rijndael-1.12/Makefile.PL @mattp-, this looks to be from yesterday's changes.

```
TypeError: $(...).attr(...) is undefined
	

GithubUrl.match=function(a){return $(a).attr('href').indexOf('github')>=0;};$.ex...
```

**Comment by mattp-** [comment]
https://github.com/CPAN-API/metacpan-web/pull/1517 should fix this.

**Comment by rwstauner** [comment]
@oalders was this fixed?

**Comment by oalders** [comment]
Yep, thanks. :)
