### ISSUE TITLE
The page for Data::Transpose doesn't display (correct) number of issues

### ISSUE THREAD

**Issue by neilbowers** [CPAN-API/metacpan-web#1519]
[Data::Transpose](https://metacpan.org/pod/Data::Transpose) has two issues in github, which have been there for a while (more than 48 hours), but no issue count is displayed in the sidebar.

**Comment by rwstauner** [comment]
ether called that last week. I'm working on it. Thanks

**Comment by neilbowers** [comment]
:+1:

**Comment by rwstauner** [comment]
The count is out of date, but it does show, now ;-)
