### ISSUE TITLE
Partial Indexing Despite PAUSE Indexing Failures Due To Database Errors

### ISSUE THREAD

**Issue by zoffixznet** [CPAN-API/metacpan-web#1521]
Hey,

Last night I got PAUSE errors when I uploaded versions 1.001003 and 1.001004 of `Test::Mojo::Role::ElementCounter`.

When I saw an IRC bot announce the 1.001004 upload (including [a link to it on MetaCPAN](https://metacpan.org/release/ZOFFIX/Test-Mojo-Role-ElementCounter-1.001004)) I figured it was just a PAUSE-related glitch, but this morning I realized MetaCPAN should NOT have indexed those modules, and in fact, looks like that is partially the case.

If you look at my author's page, https://metacpan.org/author/ZOFFIX, you can see the latest version for the module is still listed as 1.001002. Installing with `cpanm` also can only fetch 1.001002 as the
lastest. However, on the distro page (https://metacpan.org/release/Test-Mojo-Role-ElementCounter) you can use the version selector to access the supposedly-unindexed 1.001003 and 1.001004 versions.

This is the failure email I got from PAUSE:

```
The following report has been written by the PAUSE namespace indexer.
Please contact modules@perl.org if there are any open questions.

  User: ZOFFIX (Zoffix Znet)
  Distribution file: Test-Mojo-Role-ElementCounter-1.001004.tar.gz
  Number of files: 27
  *.pm files: 1
  README: Test-Mojo-Role-ElementCounter-1.001004/README
  META-File: Test-Mojo-Role-ElementCounter-1.001004/META.yml
  META-Parser: Parse::CPAN::Meta 1.4414
  META-driven index: yes
  Timestamp of file: Tue May  5 22:15:28 2015 UTC
  Time of this run: Tue May  5 22:17:49 2015 UTC

Status of this distro: Database error
=====================================

The following packages (grouped by status) have been found in the distro:

Status: Database error
======================

     module : Test::Mojo::Role::ElementCounter
     version: undef
     in file: lib/Test/Mojo/Role/ElementCounter.pm
     status : The PAUSE indexer could not store the indexing result in
             the DB due the following error: C< Lock wait timeout
             exceeded; try restarting transaction >. Please report the
             case to the PAUSE admins at modules@perl.org.

__END__
```

**Comment by rwstauner** [comment]
MetaCPAN indexes releases independently of PAUSE, so if there was a database error that kept PAUSE from indexing your release, if it still makes it to the cpan mirrors, MetaCPAN will try to index it.
However, it won't be marked as "latest" until PAUSE puts the version in `02packages` (which is the point at which `cpanm` would install it by name).

So, what do you propose should work differently?

**Comment by perlancar** [comment]
BTW, on the other hand, I've seen cases where:

1. upload X-1.23 to PAUSE, got database error
2. issue reindex for X-1.23 on PAUSE, indexing succeeds
3.  X-1.23 still doesn't show up/get indexed on MetaCPAN (MetaCPAN is still showing older version)

I will try to report this again the next time this incident happens to me.

Any idea what might have caused this, or how to resolve it?
