### ISSUE TITLE
Sort by size in browser doesn't sort numerically

### ISSUE THREAD

**Issue by sjn** [CPAN-API/metacpan-web#1523]
To reproduce this bug, do the following steps:

1. Browse to a directory with files in different sizes (1k, 10k, etc.). Example: https://metacpan.org/source/MARKOV/XML-Compile-1.48/t
2. Sort list by descending size
3. Tada!

Misconfiguration of the table sorting jQuery plugin, perhaps?

- Salve

**Comment by oalders** [comment]
Looks like the fix may be something like this: http://stackoverflow.com/a/5967371/406224

**Comment by haarg** [comment]
Fixed by a1c297500e76b9d012aaeafa21d67dc5ca0c4d00
