### ISSUE TITLE
search.mcpan.org no longer works correctly for perldoc links

### ISSUE THREAD

**Issue by oschwald** [CPAN-API/metacpan-web#1528]
Previously links from [this extension](https://chrome.google.com/webstore/detail/meta-cpan-redirect/blakeebdldmplhhegjofiaidnijmiphj?hl=en) worked with MetaCPAN worked, but I think some change to MetaCPAN broke them recently. For instance, if I do a Google search for Test::More, I get the link `http://search.cpan.org/perldoc/Test::More`. The extension [transforms this](https://github.com/bvierra/chrome-metacpanredirect/blob/master/background.js) into `http://search.mcpan.org/perldoc/Test::More`. I then end up at `https://metacpan.org/perldoc/Test::More`, which is a broken link.

@oalders suggested I open this issue.

**Comment by oalders** [comment]
Fixed via https://github.com/CPAN-API/metacpan-puppet/commit/a9a8764876425fd2d49ca4702127bc2612a59cd7
