### ISSUE TITLE
RTL characters in user names break layout.

### ISSUE THREAD

**Issue by kentfredric** [CPAN-API/metacpan-web#1532]
This is not so much "complaint" from me as an intent to document behaviour.

I have injected an RTL character into my metacpan metadata, and amusing things happen as a consequence:

![sn109](https://cloud.githubusercontent.com/assets/44790/7783662/51b87b2c-019d-11e5-826f-9ddde05522f5.png)
![sn108](https://cloud.githubusercontent.com/assets/44790/7783664/51bbc5b6-019d-11e5-934a-fd31c07b1d98.png)
![sn107](https://cloud.githubusercontent.com/assets/44790/7783663/51b98f8a-019d-11e5-9605-c12fdf8a5263.png)
![sn106](https://cloud.githubusercontent.com/assets/44790/7783665/51bda002-019d-11e5-8d0c-7f85c9d8793e.png)
![sn105](https://cloud.githubusercontent.com/assets/44790/7783666/51c0a0b8-019d-11e5-9e0e-2220436c2416.png)
![sn104](https://cloud.githubusercontent.com/assets/44790/7783667/51c1081e-019d-11e5-9777-fe3de5d15a7b.png)
![sn103](https://cloud.githubusercontent.com/assets/44790/7783668/51dfb106-019d-11e5-9398-2d0983bd7364.png)

**Comment by ranguard** [comment]
Think fixed with 8cdd848ef658a453cffbe57c95d1638501260398 and feb33f8062ef5d4ab056ade9da48aa86931de817
