### ISSUE TITLE
Dependencies links assume they are all in the repository

### ISSUE THREAD

**Issue by robrwo** [CPAN-API/metacpan-web#1534]
When one runs MetaCPAN on a private repository, the list of dependencies links to all modules as if they are in that repository.  Ideally, it would show links to the local repo if the dependency is in that repo, and to MetaCPAN otherwise.

**Comment by oalders** [comment]
Running a local MetaCPAN is, at this point, not officially supported, but also not in any way discouraged.  It would be great to see this working, but there's no bandwidth from core MetaCPAN devs to work on it.  Patches would be most welcome.
