### ISSUE TITLE
Shift+Enter for lucky searching broken

### ISSUE THREAD

**Issue by Smylers** [CPAN-API/metacpan-web#1539]
Using `Shift`+`Enter` for going straight to a module's docs isn't very lucky at the moment.

As a non-logged-in user:

1. Go to https://metacpan.org/
2. Type a module name, such as “Path::Tiny”.
3. Note the module name showing up in the instant results box.
4. Press `Shift`+`Enter`.
5. End up at https://metacpan.org/account/logout, instead of the module's docs. There's a mysterious “1” in the search box and the error “Forbidden: You don't have permission to access this resource.”:
![metacpan_forbidden_1](https://cloud.githubusercontent.com/assets/598534/7957700/605e58c6-09e1-11e5-80bd-b90322ca0620.png)

If at step 4 you click on the module name in the instant results list (instead of pressing `Shift`+`Enter`), it takes you as expected to the module's docs.

Since the erroneous URL has ‘logout’ in it, I also tried logging in and redoing the search, to see if that was luckier. It isn't, though it is different: you end up logged out and back at the homepage.

**Comment by rwstauner** [comment]
Thanks for reporting!
