### ISSUE TITLE
Diff option to ignore line ending conventions

### ISSUE THREAD

**Issue by DrHyde** [CPAN-API/metacpan-web#1542]
[This diff of EU::MM 6.57_05 to 6.58](https://metacpan.org/diff/file?target=CHORNY/ExtUtils-MakeMaker-6.57_05/&source=MSCHWERN/ExtUtils-MakeMaker-6.58/) is confusing as hell, it shows WAY more changes than there actually are, because it appears that the two versions of the distribution use different line ending conventions. eg it says that lib/ExtUtils/MM_Darwin.pm was completely replaced with a file of the same length and which at first glance appears to have the same content.

Please add an option to turn on the `--ignore-all-space` option. I think that option should even be turned on by default given that perl isn't whitespace sensitive.

**Comment by haarg** [comment]
#813

**Comment by ranguard** [comment]
Closing as is on wishlist, just needs someone to impliment
