### ISSUE TITLE
Latest version of DZP-ChangelogFromGit-CPAN-Changes is indexed but previous version is displayed

### ISSUE THREAD

**Issue by ioanrogers** [CPAN-API/metacpan-web#1543]
Hi,

I recently uploaded a new version of a module. It has been indexed on PAUSE, shows up correctly on s.c.o and explorer.cpan.org /v0/release/Dist-Zilla-Plugin-ChangelogFromGit-CPAN-Changes shows the correct metadata. It also shows up on the search page:
https://metacpan.org/search?q=Dist-Zilla-Plugin-ChangelogFromGit-CPAN-Changes

However, the main release page only shows the previous release:
https://metacpan.org/release/Dist-Zilla-Plugin-ChangelogFromGit-CPAN-Changes
and the latest version is not in the version dropdown.

I did change the version number scheme if that helps.
Thanks

**Comment by rwstauner** [comment]
I see 0.106, released on the 6th.
If you see something different b/t the search page and the release page, it
sounds like a browser caching issue.
Can you empty cache and reload?

**Comment by ioanrogers** [comment]
Oh, you're right , a hard refresh fixed it. The browser was getting 304s.

**Comment by rwstauner** [comment]
refs #1522
