### ISSUE TITLE
"Install instructions" link doesn't work

### ISSUE THREAD

**Issue by ranguard** [CPAN-API/metacpan-web#1547]
This link on any page doesn't seem to do anything (OS X, Chrome and Safari)...

![log-report-lexicon-1 04_-_log__report_translation_table_management_-_metacpan org](https://cloud.githubusercontent.com/assets/60391/8166883/827fac56-1392-11e5-855d-32f7e6a26384.png)

Didn't see any errors in console, just nothing.

Used to work, from https://github.com/CPAN-API/metacpan-web/pull/1484/files

**Comment by oalders** [comment]
Sample URL?

**Comment by ranguard** [comment]
Bah, tested 3 and they were all broken... so thought it was site wide (just found one that was ok)... anyway.. example:

https://metacpan.org/release/VANSTYN/RapidApp-1.0500

**Comment by haarg** [comment]
It doesn't work on the release page, only on the module pages.  I noted this in my comments on the PR.

https://github.com/CPAN-API/metacpan-web/pull/1484#issuecomment-93708543

**Comment by ranguard** [comment]
@sunnypatel4141 Please could you have a look into this. Thanks
