### ISSUE TITLE
Module not indexed on API

### ISSUE THREAD

**Issue by satoshi** [CPAN-API/metacpan-web#1553]
Hi,

I've uploaded a small module called RPM::NEVRA.  It is on MetaCPAN:
https://metacpan.org/pod/RPM::NEVRA

and also here:
https://cpan.metacpan.org/modules/02packages.details.txt

However, this URL returns 404:
http://api.metacpan.org/v0/release/SYAGI/RPM-NEVRA-v0.0.2

Please advise what the issue might be; is it a matter of indexing not happening yet?

**Comment by rwstauner** [comment]
If it's on metacpan.org that means it's available in the api.
The api slug is based on the name of the uploaded archive (which doesn't have the `v` on it):
https://api.metacpan.org/v0/release/SYAGI/RPM-NEVRA-0.0.2

**Comment by satoshi** [comment]
@rwstauner  Silly me, thanks for the clarification!

**Comment by satoshi** [comment]
Just to add more context here, it looks like there is a bug where module-starter converted my version string of "0.0.2" into "v0.0.2" in the metadata but not in the tarball filename.  The result was MetaCPAN indexed without the 'v' whereas FPM was looking at the URL with a 'v'.  In any event, this is not a bug on the MetaCPAN side.

**Comment by oalders** [comment]
@satoshi, thanks for the additional information. :)
