### ISSUE TITLE
New radio buttons unclear

### ISSUE THREAD

**Issue by kentfredric** [CPAN-API/metacpan-web#1554]
The purpose of the radiobuttons listed "module" and "author" are very vague and eat up parts of the page that are useful.

If you don't know what they're for, then you get weird results:

![sn154](https://cloud.githubusercontent.com/assets/44790/8540159/07a1c3ec-24d7-11e5-86fe-d7991ab88cb8.png)
![sn153](https://cloud.githubusercontent.com/assets/44790/8540160/07a8d0e2-24d7-11e5-9303-a1b8683d5406.png)

Not until I went to complain and saw the commit message did it become slightly clear:

![sn155](https://cloud.githubusercontent.com/assets/44790/8540182/398608be-24d7-11e5-99c5-055d70550428.png)

Only then did it become obvious how they worked.

**Comment by ranguard** [comment]
I get this on Chrome on a mac:
![search_for__data__page__-_metacpan_org](https://cloud.githubusercontent.com/assets/60391/8541403/e07ef088-2485-11e5-9d58-ab0e0c564cfe.png)

**Comment by oalders** [comment]
ping @danmcc

**Comment by rwstauner** [comment]
Linux Chrome, also.

>   I guess I only looked at firefox. :\

**Comment by oalders** [comment]
Looks fine on my OS X Chrome `Version 43.0.2357.130 (64-bit)`

**Comment by danmcc** [comment]
Weird!  I'll take a peek.  I'm totally open to other UI implementations, too.  We could have a select list between the text field and the search button sort of like [Shutterstock](http://www.shutterstock.com/) does.

**Comment by ranguard** [comment]
+1 for shutterstock drop down style selector

**Comment by oalders** [comment]
+1 for Shutterstock style.  Didn't even know that was an option. :)

**Comment by oalders** [comment]
@kentfredric care to comment on the UI in #1569 ?

**Comment by ranguard** [comment]
No feedback received - closing
