### ISSUE TITLE
Add a blog for new CPAN releases

### ISSUE THREAD

**Issue by salva** [CPAN-API/metacpan-web#1555]
Let module authors include in some way announcements into their module distributions and then in metacpan, show those aggregated in a news page.

Most modules already have some kind of Changes files, but those are usually for reference and boring and don't include the stories, motivations and plans behind the new version.

What I mean is something, that everybody would like to read in the morning to get a feel of what is happening in CPAN.

**Comment by oalders** [comment]
@salva are you offering to implement this or submitting this as a wishlist item?

**Comment by salva** [comment]
Wishlist item!

**Comment by ranguard** [comment]
Added to wishlist
