### ISSUE TITLE
profile data on web does not match api and settings

### ISSUE THREAD

**Issue by patch** [CPAN-API/metacpan-web#1563]
I can update my profile data and it is reflected in the api:
http://api.metacpan.org/author/PATCH

But is not reflected in my web profile:
https://metacpan.org/author/PATCH

The following fields have changed: Name, Website, Twitter, LinkedIn

Note that I have never been able to display the ++’s on my profile. I just followed the steps in #1384 to no avail.

**Comment by patch** [comment]
Never mind! Some sort of caching was going on. It's fine in an incognito window.

**Comment by patch** [comment]
Interesting: as soon as I logged out of metacpan the changes took affect in my primary browser. Perhaps that busted the cache.

**Comment by patch** [comment]
And now I can see all me favorites, for the first time ever!

**Comment by oalders** [comment]
@patch thanks for the followup.  :)  @ranguard pinging you as our resident caching expert!
