### ISSUE TITLE
Alpha and legacy distribution pod links to latest stable pod

### ISSUE THREAD

**Issue by dagolden** [CPAN-API/metacpan-web#1567]
Pod links in alphas or old (previously indexed, but no longer latest stable) distributions always link to the target via the 'pod' endpoint (e.g. `https://metacpan.org/pod/Foo::Bar`).

This means every Pod link in old/alpha dists always jumps to the latest stable documentation (or gives a "Not found" error if it doesn't exist in the stable release).

`search.cpan.org` has been doing this correctly for a very long time.  It's a shame that metacpan hasn't figured it out yet.

**Comment by ranguard** [comment]
Think now fixed - please comment if not and will re-open
