### ISSUE TITLE
Default points to previous version of List::Uniq, not the latest (0.21.0)

### ISSUE THREAD

**Issue by gsullivan** [CPAN-API/metacpan-web#1568]
https://metacpan.org/pod/List::Uniq does not point to the latest version of the List::Uniq module.  It points to version 0.20 (uploaded in 2010), but it should point to version 0.21.0 (2014).

I suspect there is something unusual about the latest version of this module because when I run the "cpan List::Uniq" command, the previous version (0.20) gets installed instead of the latest version (0.21.0).

**Comment by haarg** [comment]
This is a problem with the versions used by the dist.  perl has two version formats, which can compare in unexpected ways.  There is the numeric form and the dotted decimal format.  0.20 is a numeric version, which is equivalent to 0.200.0 in dotted decimal form.  0.21.0 is a dotted decimal version, which is equivalent to 0.021000 in numeric form.  Based on this, metacpan (and PAUSE, which controls the index used by "cpan List::Uniq") are doing the correct thing.  This is pretty shitty, but the correct place to fix this would be in the dist itself.  There is an RT ticket for this: https://rt.cpan.org/Public/Bug/Display.html?id=106262
