### ISSUE TITLE
"Contributors > Show them" shows raw Pod

### ISSUE THREAD

**Issue by eserte** [CPAN-API/metacpan-web#1570]
If I click on "Show them" under "and 1 contributors" on https://metacpan.org/pod/Daemon::Control, then raw Pod appears:
```
 =over 4 
```
It looks like the CONTRIBUTORS section should run through Pod::Text or so.

**Comment by rwstauner** [comment]
That's actually a bug in the release META and warrants a ticket for that dist.
https://metacpan.org/source/SYMKAT/Daemon-Control-0.001007/META.yml

**Comment by rwstauner** [comment]
https://rt.cpan.org/Ticket/Display.html?id=106291

**Comment by rwstauner** [comment]
So to clarify, it's not showing pod, it's verbatim text from what is in the META file.

**Comment by eserte** [comment]
Ah. Sorry for the noise then.
