### ISSUE TITLE
the dependencies doesn't find Devel::CheckLib for Authen::SASL::XS

### ISSUE THREAD

**Issue by jhi** [CPAN-API/metacpan-web#1571]
Using either

(1) cpanm(inus) with the metacpan API (the default)

or

(2) the labs at https://metacpan.org/lab/dependencies?module=Authen-SASL-XS

the Devel::CheckLib is not found as a dependency of Authen::SASL::XS, even though it most certainly is:

http://cpansearch.perl.org/src/GBARR/Authen-SASL-XS-1.00/META.yml
...
build_requires:
    Devel::CheckLib:  0

**Comment by rwstauner** [comment]
The data is present in the api:
https://explorer.metacpan.org/?url=/release/GBARR/Authen-SASL-XS-1.00

So it would seem (1) and (2) aren't using it.
