### ISSUE TITLE
LICENCE files are not shown

### ISSUE THREAD

**Issue by karenetheridge** [CPAN-API/metacpan-web#1573]
LICENCE files are not included in the top level file listing of a distribution -- e.g. https://metacpan.org/release/Dist-Zilla-PluginBundle-Author-ETHER

Dist::Zilla 5.038 now allows for licence files to be produced using this filename.
Module::CPANTS::Analyse also recognizes this as a valid spelling.

**Comment by karenetheridge** [comment]
fantastic, my distributions are showing LICENCE now!

**Comment by rwstauner** [comment]
\o/
