### ISSUE TITLE
BUG.pod, a part of example, shown in "Documentation" section

### ISSUE THREAD

**Issue by van-de-bugger** [CPAN-API/metacpan-web#1575]
Have a look at [`Hook`](https://metacpan.org/release/VDB/Dist-Zilla-Plugin-Hook-0.006) module. Its page has "Examples" section, which lists all the example files. The list is correct.

However, one file, `ex/TemplateVariables/BUGS.pod`, also listed in "Documentation" section as `ex::TemplateVariables::BUGS`. This is not correct, this file is an example, **not** documentation.

BTW, this problem may be related to [Documentation heuristic inconsistencies](https://github.com/CPAN-API/metacpan-web/issues/1509).

**Comment by ranguard** [comment]
Closing as dupe of #1509
