### ISSUE TITLE
Issue tracker link (possibly others) needs dist name to be URL encoded

### ISSUE THREAD

**Issue by Grinnz** [CPAN-API/metacpan-web#1577]
https://metacpan.org/release/Text-Tabs+Wrap

The issue tracker link for this dist is https://rt.cpan.org/Public/Dist/Display.html?Name=Text-Tabs+Wrap, but the actual issue tracker is at https://rt.cpan.org/Public/Dist/Display.html?Name=Text-Tabs%2BWrap. This is most likely also needed for the other sidebar links where the dist name is used in a URL query parameter, like cpantesters and cpanratings.

**Comment by rwstauner** [comment]
I think that covers it.
Thanks for reporting!
