### ISSUE TITLE
Truncate Changes at top of distribution page if long

### ISSUE THREAD

**Issue by dagolden** [CPAN-API/metacpan-web#1585]
For short changes, having the Changes at the top (#1510, #1581) is fine.  But it's a PITA for long ones.  E.g.:  https://metacpan.org/release/DOY/Moose-2.0000

Changes are something people need to see usually just once, whereas the list of documentation/module links are used frequently.  Putting Changes at the top is inefficient use of screen real estate.

If you really think it's best at the top, then I suggest putting only the top N lines of Changes at the top (10?  20?) and putting a "For the full list, see the Changes file" hyperlink at the point of truncation.

**Comment by oalders** [comment]
I think we need to do this.  Just not quite sure what the best UI for it is.

**Comment by haarg** [comment]
I'd rather have something collapsible than having a link.

**Comment by rjbs** [comment]
Either way, I hit [App-PipeFilter](https://metacpan.org/release/App-PipeFilter) yesterday and thought I was seeing a crash report or something.  When this goes wrong, it goes really wrong.

**Comment by oalders** [comment]
Fixed via #1600
