### ISSUE TITLE
Make the "whatsnew" section stand out more

### ISSUE THREAD

**Issue by oalders** [CPAN-API/metacpan-web#1588]
Aside from fixing the issue with Changesets which are too large, we need to set this apart a bit.  If I just put it into a well, it doesn't play terribly nicely with the right panel.

<img width="1225" alt="screenshot 2015-08-28 23 01 00" src="https://cloud.githubusercontent.com/assets/96205/9560265/ebd39dae-4dd8-11e5-8396-c2baf76db796.png">

**Comment by haarg** [comment]
The overlap with the sidebar can be dealt with pretty easily by using a margin.

**Comment by oalders** [comment]
Not being well versed in CSS, can you point me at where I'd be adding the margin?
