### ISSUE TITLE
RISC-Workload POD is not shown

### ISSUE THREAD

**Issue by gsullivan** [CPAN-API/metacpan-web#1593]
I cannot see the POD for this module:
https://metacpan.org/release/RISC-Workload

The lib/RISC/Workload.pm does have POD, and I can see it on http://search.cpan.org/~katelynn/RISC-Workload/lib/RISC/Workload.pm.

Is there something about the distribution that causes this issue?

I do notice several oddities about the dist.  The POD does not have a "=head1 NAME" section.  The uploaded PAUSE file is a .zip file, not a tar.gz file.  Also, it doesn't install for me using the "cpan RISC::Workload" command.

**Comment by haarg** [comment]
This is most likely due to the lack of a NAME section.

It appears that the dist was packaged by zipping the working dir rather than using EUMM's dist target.  Additionally, the filename of the Makefile.PL is wrong.  It's Makefile.pl instead, which will only work on case insensitive filesystems.

**Comment by gsullivan** [comment]
The module author uploaded a new version (RISC-Workload-0.02), and now I can see the POD.  A NAME section was added to the POD.
