### ISSUE TITLE
Also recognize P5#<number> as $rt_perl_base [wishlist]

### ISSUE THREAD

**Issue by ribasushi** [CPAN-API/metacpan-web#1595]
The addition would look like
```
|
  \brt\.perl\.org\s+\#
|
  \bP5\#
```
around line 61 in [this block](https://github.com/CPAN-API/metacpan-web/blob/master/lib/MetaCPAN/Web/Model/API/Changes.pm#L54-L79)

**Comment by haarg** [comment]
Seems sensible.  Do you have an existing example of this in a change log?

**Comment by ribasushi** [comment]
@haarg Not yet, because I didn't want to ship something that won't be supported (there's no way to retroactively fix a changelog). But what I am having in mind [is this](https://github.com/dbsrgits/dbix-class/blob/trv/Changes#L43) (note - unstable hash, will be rebased away soon)

**Comment by haarg** [comment]
This feature has been added.

**Comment by ribasushi** [comment]
Excellence, thanks!
