### ISSUE TITLE
Radio buttons on front page distorted

### ISSUE THREAD

**Issue by kentfredric** [CPAN-API/metacpan-web#1598]
This is a new issue I just started noticing today, but I don't see any commit to blame for it;

![snapshot46](https://cloud.githubusercontent.com/assets/44790/10414275/fa1fd212-7027-11e5-8a7b-fc0f36235857.png)

**Comment by haarg** [comment]
What browser, version, and operating system are you seeing this in?  I suspect #1608 will fix this.

**Comment by rwstauner** [comment]
I actually saw this on firefox for android.

**Comment by kentfredric** [comment]
Firefox 42.0b6 
Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0

w/ Gentoo Linux.

**Comment by kentfredric** [comment]
Confirming fixed.
