### ISSUE TITLE
Obsolete Changes file displayed

### ISSUE THREAD

**Issue by ronsavage** [CPAN-API/metacpan-web#1601]
For e.g. GraphViz2, V 2.37 is on CPAN, and the Changes file is up-to-date, but MetaCPAN only shows the Changes file for V 2.34.

**Comment by haarg** [comment]
Possibly a browser caching issue?  I can't reproduce this problem.

**Comment by ronsavage** [comment]
Hmmm. A Chrome issue it must be. I don't have the problem with FF.
The link https://metacpan.org/release/GraphViz2 took me to V 2.34 under Chrome, and V 2.37 under FF. After repeatedly refreshing the correct version showed up. Thanx.
I'll close the issue.
