### ISSUE TITLE
There seems to be no way to "latest-link" to an unindexed module

### ISSUE THREAD

**Issue by ribasushi** [CPAN-API/metacpan-web#1603]
I am looking for a way to link to the **latest version** of the [source of DBIx::Class::Storage::DBIHacks](https://metacpan.org/source/RIBASUSHI/DBIx-Class-0.082820/lib/DBIx/Class/Storage/DBIHacks.pm). So far no matter what I tried the only thing that works is the version-specific link. Am I missing an obvious incantation or does this need work to become possible?

Cheers

**Comment by oalders** [comment]
You'll need the version-specific link at this point.  There's no "latest" flag on unindexed dists, so this is the best we have right now.

**Comment by ribasushi** [comment]
Nod. Thanks!
