### ISSUE TITLE
Metacpan css and javascript gives 404, does not load

### ISSUE THREAD

**Issue by mbeijen** [CPAN-API/metacpan-web#1604]
See screenshot:

![metacpan_css](https://cloud.githubusercontent.com/assets/659504/10518574/63fcc2ac-7362-11e5-9ba6-aefe50590984.png)

**Comment by oalders** [comment]
There's an issue around static assets and flushing the Fastly caching.  This should actually get better moving forward.  In the meantime it'll have to be hard refreshes of the browser cache. cc @ranguard @haarg .
