### ISSUE TITLE
search button now occupies its own line

### ISSUE THREAD

**Issue by kentfredric** [CPAN-API/metacpan-web#1605]
This is a new behaviour I noticed today.

It wasn't occurring when #1550 was filed.

But the "Search" button now wraps creating additional vertical space.

![snapshot52](https://cloud.githubusercontent.com/assets/44790/10556258/34699fc2-74db-11e5-97f6-de7a9b92bbb3.png)

**Comment by haarg** [comment]
I've seen this same issue in Firefox on OS X.  I wasn't able to track it down to a change in metacpan, but I believe I have a fix for it.
