### ISSUE TITLE
link name for module epub links

### ISSUE THREAD

**Issue by karenetheridge** [CPAN-API/metacpan-web#1610]
I got this email regarding Catalyst-Manual:

> So far a great read. I went to Meta::CPAN and hit the EPUB link on all the chapters. Looks great on an iPad mini in iBooks, but one little thing - each download loads up with the title Catalyst-Manual-5.9009.  
> Can you fix the metadata to get the subchapter name in there or is thata MetaCPAN thing?

**Comment by haarg** [comment]
We are only providing links to the EPUB/MOBI files.  [perlybook.org](http://perlybook.org) handles the generation of the files.  This should be reported at https://github.com/reneeb/cpan2ebook/issues
