### ISSUE TITLE
Final dot is falsely added to URL

### ISSUE THREAD

**Issue by benkasminbullock** [CPAN-API/metacpan-web#1611]
Example page:

https://metacpan.org/pod/Text::Table::Manifold

at this location:

https://metacpan.org/pod/Text::Table::Manifold#Copyright

Text where URL is falsely added:

	All Programs of mine are 'OSI Certified Open Source Software';
	you can redistribute them and/or modify them under the terms of
	The Artistic License 2.0, a copy of which is available at:
	http://opensource.org/licenses/alphabetical.

The final dot after "alphabetical" is added to the URL, resulting in a bad link:

http://opensource.org/licenses/alphabetical.

Without the dot, the link works correctly:

http://opensource.org/licenses/alphabetical

In my experience a final dot is rarely part of a URL. I suggest truncating the URL finder before the above final dot when the dot is followed by a carriage return or linefeed or other whitespace.

**Comment by haarg** [comment]
Fixed in 45d72f7a19c0cfa2373e033a637bbf93597be18a
