### ISSUE TITLE
Source highlighting suggestion - Modules used via Mojo::Base

### ISSUE THREAD

**Issue by Grinnz** [CPAN-API/metacpan-web#1615]
As it is very common in the Mojo ecosystem to set up inheritance with `use Mojo::Base 'Some::Module';` maybe this Some::Module could be turned into a link like is done with `use parent` and `use base`? See for example https://metacpan.org/source/SRI/Mojolicious-6.29/lib/Mojolicious.pm#L2

**Comment by haarg** [comment]
Fixed by 16beff13d3c581872d4c1827de91f53e2b3517c3
