### ISSUE TITLE
can metacpan be made to index DBIx-Class-Manual-SQLHackers?

### ISSUE THREAD

**Issue by wchristian** [CPAN-API/metacpan-web#1617]
http://search.cpan.org/~ribasushi/DBIx-Class-Manual-SQLHackers-1.3/

Right now it's not indexed, apparently because it has no .pm files at all in it. Is that something that can be solved in metacpan?

**Comment by haarg** [comment]
metacpan won't index it until it is indexed in PAUSE.  provides metadata needs to be added to the dist for that.

**Comment by oalders** [comment]
@ribasushi, is there a compelling reason not to include a .pm file in this distribution?

**Comment by ribasushi** [comment]
@oalders Yes there is: `perl -MSomeDocThing` should not return 1. And in general - plain separation of concerns.

The part about it not being in 06 is a separate matter, and I dropped the ball on addressing this. Stay tuned for more info in 2~3 days.

**Comment by ranguard** [comment]
Please comment and we'll reopen if still and issue after sorting 06 perms
