### ISSUE TITLE
B::DeparseTree not showing up

### ISSUE THREAD

**Issue by rocky** [CPAN-API/metacpan-web#1620]
PAUSE doesn't give me an error in indexing and uploading. I am getting CPANTS test reports,

http://search.cpan.org/~rocky/B-DeparseTree-v2.0.1/ does show this. (Yeah, I have read what you wrote about how thiis doesn't mean anything with respect to metacpan.)  

It is not showing up in  https://cpan.metacpan.org/modules/02packages.details.txt but I haven't an idea why. What should I do?

**Comment by ranguard** [comment]
Please check your spam folder from PAUSE indexing, then check permissions from within PAUSE.

If it's not in the 02packages file then we won't make it searchable IIRC.. you can see we have it:

https://metacpan.org/release/ROCKY/B-DeparseTree-v2.0.1

Thanks
