### ISSUE TITLE
schema.org microdata broken

### ISSUE THREAD

**Issue by mephinet** [CPAN-API/metacpan-web#1629]
The schema.org microdata that was introduced with pull request #864 is currently broken (probably caused by a UI rework), as can be seen by [Google structured data test tool](https://developers.google.com/structured-data/testing-tool?url=https%253A%252F%252Fmetacpan.org%252Fpod%252FMoose&filter=RICH_SNIPPETS_SOFTWARE) not correctly showing 1 app with name, author, url, etc, but instead two apps with basically no data.

**Comment by mephinet** [comment]
(feel free to assign this issue to me)

**Comment by oalders** [comment]
@mephinet I can't properly assign this to you without you being in the CPAN-API org, but I _can_ say, "would you please fix this"? ;)

Help is also available on #metacpan on irc.perl.org if you have any questions.

**Comment by mephinet** [comment]
yes I will ;-)

**Comment by oalders** [comment]
:+1:
