### ISSUE TITLE
Some source listings lack *both* syntax highlighting

### ISSUE THREAD

**Issue by kentfredric** [CPAN-API/metacpan-web#1631]
https://metacpan.org/source/MIYAGAWA/App-cpanminus-1.7039/lib/App/cpanminus/fatscript.pm 

There's neither syntax highlighting or line numbers available in this file, which makes it impossible to link to specific line numbers.

I suspect this is related to the old problem of the syntax highlighter eating browser time and not working on very large files, but I couldn't find a relevant bug.

**Comment by haarg** [comment]
The line numbers are provided by the syntax highlighter, which is intentionally disabled for files that are large enough.  It may be possible to use a different "plain text" syntax for the highlighter, so that it could be enabled on large files without causing browser slowdowns.

**Comment by ranguard** [comment]
We don't have a bug as that was the SOLUTION (not using the highlighter). If someone has a better highlighter and the time to implement we'd look at it
