### ISSUE TITLE
github-meets-cpan author url wrong

### ISSUE THREAD

**Issue by abraxxa** [CPAN-API/metacpan-web#1635]
The github-meets-cpan author url in the profiles section on the left hand side of the author page is incorrect because the CPAN ID is lowercase instead of uppercase.
For example on https://metacpan.org/author/ABRAXXA it should point to http://gh.metacpan.org/user/ABRAXXA whereas it points to http://gh.metacpan.org/user/abraxxa.
gh.metacpan.org doesn't like this and responds with a http 500.

**Comment by rwstauner** [comment]
I fixed the error: https://github.com/CPAN-API/github-meets-cpan/commit/773c8e7dfccb8c07b35e107a220ad0d35bd1d860
and added a redirect: https://github.com/CPAN-API/github-meets-cpan/commit/15e7627c021c2fa8d332c32c15da14aa003979ac
but I cannot deploy at the moment.

Alternatively you are free to change the case in your metacpan profile.

**Comment by rwstauner** [comment]
This has been deployed.
