### ISSUE TITLE
Test report counts severely out of sync

### ISSUE THREAD

**Issue by ribasushi** [CPAN-API/metacpan-web#1636]
At the time this ticket was filed the [metacpan page of DBIC](https://metacpan.org/release/RIBASUSHI/DBIx-Class-0.082820) shows
```
Testers (3297 / 30 / 0)
```
yet the [cpantesters matrix](http://matrix.cpantesters.org/?dist=DBIx-Class+0.082820) has
```
PASS: 4817
FAIL: 64
UNKNOWN: 10
```

**Comment by haarg** [comment]
I believe this is the same issue as #1630

**Comment by ranguard** [comment]
Closing - dupe
