### ISSUE TITLE
Reindexes not showing on search

### ISSUE THREAD

**Issue by singingfish** [CPAN-API/metacpan-web#1638]
I reindexed Plack::Middleware::SSI today, having been given comaint a couple of weeks ago, but not needing to re-upload a new dist (i.e. my unauthorised release is now authorised).  search.cpan.org picks up the reindex request from pause.perl.org but metacpan does not, and nether does the dist appear on the /recent page on metacpan making me think this is a bug.

**Comment by oalders** [comment]
MetaCPAN doesn't (yet) know about PAUSE re-indexing, so you just have to ping us to re-index for you.  I've just done so and it's there now https://metacpan.org/pod/Plack::Middleware::SSI  If this happens again, you can either open another ticket or ping us on IRC. :)
