### ISSUE TITLE
SSL issue during download

### ISSUE THREAD

**Issue by pputnik** [CPAN-API/metacpan-web#1639]
Incorrect certificate:

$ wget https://cpan.metacpan.org/authors/id/P/PM/PMQS/IO-Compress-2.045.tar.gz
--2016-01-24 13:16:50--  https://cpan.metacpan.org/authors/id/P/PM/PMQS/IO-Compress-2.045.tar.gz
Resolving cpan.metacpan.org... 23.235.43.129, 23.235.43.192
Connecting to cpan.metacpan.org|23.235.43.129|:443... connected.
ERROR: certificate common name `a.ssl.fastly.net' doesn't match requested host name `cpan.metacpan.org'.
To connect to cpan.metacpan.org insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.

**Comment by ranguard** [comment]
This works fine for me from OSX and Debian

The certificate is a (SAN)[https://en.wikipedia.org/wiki/SubjectAltName] certificate, so one certificate supporting multiple domain names so I'm guessing what ever OS/setup you have is something that doesn't support that?

Please comment with more details and I'll open again if you haven't been able to solve from your side

**Comment by pputnik** [comment]
Hello,

thank you for the quick response.

$ cat /etc/redhat-release
CentOS release 5.11 (Final)

$ uname -a
Linux putnik.net.ua 2.6.38.2.domU.x86_64 #1 SMP Wed Mar 30 13:47:22 EEST 2011 x86_64 x86_64 x86_64 GNU/Linux

$ yum update  -y -x mysql*
(...)
No Packages marked for Update

$ wget --version
GNU Wget 1.11.4 Red Hat modified

Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic#xemacs.org>.
Currently maintained by Micah Cowan <micah#cowan.name>.

**Comment by ranguard** [comment]
I think you need to get a newer version of wget

https://lists.gnu.org/archive/html/bug-wget/2011-11/msg00021.html

Suggests wget 1.13.x version works with SAN's, otherwise you'll have to use the --no-check-certificate option, or a different tool
