### ISSUE TITLE
Install instructions are wrong if you're not viewing a module

### ISSUE THREAD

**Issue by pink-mist** [CPAN-API/metacpan-web#1641]
For instance, the ```Install instructions``` link in the lefthand sidebar of https://metacpan.org/pod/distribution/Perl-Tidy/bin/perltidy tells you you can install this with ```cpanm perltidy```, which is wrong. You need ```cpanm Perl::Tidy``` in this case.

If you think this is a duplicate of #1627, please go ahead and close this issue. (I was a bit confused about the exact issue that one was reporting)

**Comment by oalders** [comment]
Good catch.  We should be using `main_module` from the `release` here.

**Comment by ranguard** [comment]
Closing as dup
