### ISSUE TITLE
Link to cpanold.chorny.net

### ISSUE THREAD

**Issue by dolmen** [CPAN-API/metacpan-web#1645]
cpanold.chorny.net is a useful tool for CPAN authors.
Example: http://cpanold.chorny.net/?a=ETHER

It would be helpful to add a link to that tool from each CPAN author page.

**Comment by oalders** [comment]
Great tool.  I was not aware of this.  A patch would be welcome.  I guess it would belong on the author page.

**Comment by ranguard** [comment]
Patch would be great
