### ISSUE TITLE
pod-to-html rendering of <code>-embedded link loses the href attribute

### ISSUE THREAD

**Issue by karenetheridge** [CPAN-API/metacpan-web#1646]
https://metacpan.org/pod/Dist::Zilla::PluginBundle::Author::ETHER (version 0.111) generates pod containing this:

```
There is also an irc channel available for users of this distribution, at
L<C<#distzilla> on C<irc.perl.org>|irc://irc.perl.org/#distzilla>.
```

(carriage returns added in snippets below for readability)

`pod2html` turns this snippet (correctly) into:

    <p>There is also an irc channel available for users of this distribution, at
    <a href="irc://irc.perl.org/#distzilla"><code>#distzilla</code> on <code>irc.perl.org</code></a>.</p>

But on metacpan.org, the rendered html is:

    <p>There is also an irc channel available for users of this distribution, at
    <a><code>#distzilla</code> on <code>irc.perl.org</code></a>.</p>

As you can see, the `href` attribute of the `a` tag is totally missing.

**Comment by haarg** [comment]
I'm pretty sure the actual problem is linking to the irc: scheme.
