### ISSUE TITLE
searching for perlvar and perlrun doesn't give perl as the first result

### ISSUE THREAD

**Issue by pink-mist** [CPAN-API/metacpan-web#1666]
If you search for either ```perlvar``` or ```perlrun``` you get a result from ```PodSimplify``` from 1996 instead of the latest perl release as first result; perl's perlvar and perlrun pages are the second result for their respective searches.

Clearly this is a relatively minor bug since the correct result does show up.

**Comment by oalders** [comment]
@pink-mist could you move this to a comment on https://github.com/CPAN-API/metacpan-web/issues/1666 ?  That's where we're tracking bad search results.

**Comment by pink-mist** [comment]
@oalders This is #1666?

**Comment by oalders** [comment]
Sorry, #1231

**Comment by pink-mist** [comment]
Alright, commented on #1231, so closing this one in preference for that one.
