### ISSUE TITLE
"Author" radio button no longer has any effect

### ISSUE THREAD

**Issue by kentfredric** [CPAN-API/metacpan-web#1668]
I can't seem to see anything that happens from selecting the "author" radiobutton.

- All it does is kills inline results entirely
- Doesn't affect the final results when you click search.

So the screenspace to support this feature has become dead-weight while the feature is broken.

A good test candiate is "Urban" due to its use in both author names and module names.

**Comment by haarg** [comment]
Switching to author changes the autocomplete to search for authors.  This is working properly for me.

**Comment by kentfredric** [comment]
User side error. 

Need to add cnstrc.com to ublock exclusion list.
