### ISSUE TITLE
Remove broken coderwall badge link

### ISSUE THREAD

**Issue by jberger** [CPAN-API/metacpan-web#1669]
Coderwall seems to no longer provide badges for remote use. I actually am even having a hard time finding that they ever did, but I do see plenty of code trying to emulate old behavior. Indeed some of those scripts are even getting a little bit old. Sounds to me they are gone.

MetaCPAN should probably remove the broken behavior, possibly replacing it with something else (are there any candidates?).

**Comment by jberger** [comment]
see the broken image at https://metacpan.org/author/JBERGER

**Comment by oalders** [comment]
Yeah, this is actually the link in the profile.  The actual fix is at https://github.com/CPAN-API/metacpan-web/pull/1663 but we've gotten into a bad habit of merging without deploying.  I'll deploy that now and we'll see if that does the trick.

**Comment by oalders** [comment]
Deployment is finished.  I think it's better now?

**Comment by jberger** [comment]
Yessir, thank you!

**Comment by jberger** [comment]
It wasn't so much the not deploying as the fix didn't seem to correspond. Thanks again

**Comment by oalders** [comment]
I just got lazy.  Thanks for the nudge.  Now I'm just hoping that deployment didn't break anything else.  :)
