### ISSUE TITLE
The changes box should include all the changes from the latest stable release.

### ISSUE THREAD

**Issue by salva** [CPAN-API/metacpan-web#1671]
Currently, when a module page is visited, it includes the set of changes for the last release, but for modules that have intermediate development releases that doesn't work well.

It would be better to show all the changes since the previous stable.

For instance, the page for [Net::SSH2 0.58](https://metacpan.org/release/SALVA/Net-SSH2-0.58) shows...

    Changes for version 0.58
         - re-released as stable

It would be much interesting to show instead the following:

    Changes for version 0.58
        - re-released as stable
    Changes for version 0.57_03
        - remove MYMETA.* from distribution
        - workaround bug in libssh2_agent_disconnect
    Changes for version 0.57_02
        - Module::Install::CheckLib was missing
    Changes for version 0.57_01
        - reimplement scp_put and scp_get methods fixing several issues
        - add support for Mac Homebrew and its keg-only OpenSSL

**Comment by oalders** [comment]
@haarg  is this possible?

**Comment by haarg** [comment]
This has been implemented.
