### ISSUE TITLE
Current release via versioned URL doesn't use versioned URL for changes link

### ISSUE THREAD

**Issue by ribasushi** [CPAN-API/metacpan-web#1675]
As the title says. Starting from [this page](https://metacpan.org/release/PYTHIAN/DBD-Oracle-1.28) there seems to be no amount of clicking that will allow me to arrive at [the desired permalink (which I constructed by hand)](https://metacpan.org/source/PYTHIAN/DBD-Oracle-1.28/Changes#L7-9)

**Comment by haarg** [comment]
The Changes link on the sidebar would give you the same content, although with a different URL.  This specific dist uses Pod in their Changes file, so the link to the file on the dist page shows a pod view.  From there, you can click the source link on the sidebar to get the exact URL you ended with.

Do you have a suggestion for what kind of improvement you would like to this?

**Comment by haarg** [comment]
Clarified the issue over IRC.  When viewing the latest release via a versioned URL (like https://metacpan.org/release/RIBASUSHI/DBIx-Class-0.082821) the Changes release on the sidebar doesn't use the versioned URL for the Changes file.  For non-latest releases it will correctly use the versioned URL.

Picking versioned vs non-versioned should be based on the URL used to visit the page, not whether it is the latest release or not.

**Comment by haarg** [comment]
Fixed in #1733

**Comment by oalders** [comment]
Fix has been deployed.  Let's re-open if there's still an issue.
