### ISSUE TITLE
How to get a css element with Selenium using a css framework ( like DevBuilder) and coding in Perl 

### ISSUE THREAD

**Issue by Chaoui05** [CPAN-API/metacpan-web#1676]
# Important, please read:

MetaCPAN's core developers need to focus on fixing bugs and improving the
existing core system.

For this reason, if you have a feature which you would like to see added (there
are loads we would love to have), please only open an issue _IF_ you are
prepared to do the work to implement it.  To be clear, we'd love to have a
bunch of really cool, new, features, but it's more important for us to focus on
keeping MetaCPAN humming along.

If you're not motivated or otherwise able to send a pull request for your cool,
new feature, please add it to our wishlist:
https://github.com/CPAN-API/cpan-api/wiki/Wishlist and someone may get to it
one day.  Maybe that person will be you!

For more details on issues and contributing please see CONTRIBUTING.md (linked
above)

**Comment by ranguard** [comment]
Hi @Chaoui05,

I think you need to open an issue with the selenium package developer, not on metacpan.

Thanks

Leo

**Comment by Chaoui05** [comment]
I did it ..No results . Maybe issue need to call others module here or some patch or implement

**Comment by ranguard** [comment]
Maybe you could try asking on IRC

#perl-help, #perl on irc.freenode.net, #perl on irc.oftc.net

**Comment by Chaoui05** [comment]
haha i did too . And iam right now there..

**Comment by Chaoui05** [comment]
Believe me. I tried almost everywhere

**Comment by oalders** [comment]
Try stackoverflow.com
