### ISSUE TITLE
Duplicate versions of https://metacpan.org/about

### ISSUE THREAD

**Issue by perigrin** [CPAN-API/metacpan-web#1684]
https://metacpan.org/about/contact and https://metacpan.org/about/search.cpan.org are both (currently) full duplicates of https://metacpan.org/about (at least as far as crawlers are concerned). This hurts the SEO of one of the better ranked pages on the site. They need a `rel="canonical"` meta-tag back to the main about page (if not a 301).

**Comment by haarg** [comment]
Where did you get those links from?  Currently, https://metacpan.org/about/anything will go to the main about page.  I'd say they should be 404s, not redirects or anything else.

**Comment by perigrin** [comment]
I'm using a SEO tool that has its own built in crawler and somehow it found
those links.

404 means that whatever was linking to them just dies, 301 at least gets
them to the information they want.

-- 
Chris Prather

**Comment by haarg** [comment]
The bad links were in the FAQ.  I've submitted a PR to fix them, as well as clean up the dispatching so we aren't allowing arbitrary path extensions.
