### ISSUE TITLE
[mi/es2] sort behavior

### ISSUE THREAD

**Issue by mickeyn** [CPAN-API/metacpan-web#1695]
we need to investigate how to fix 'sort' behavior in queries for ES 2.3.
in t/model/release.t there's an assumption that a query (that lives in `Model::API::Release::modules`) with a `sort => [ 'documentation', 'path' ]` will give the same results of the equivalent Perl sorting: 
```
sort {  $a->{documentation} cmp $b->{documentation}
             or $a->{path} cmp $b->{path}  }
```
which is not the case:
1. when elements have no value they are not placed at the front like in Perl
2. the result sorting of `['HTTP::CookieMonster::Cookie','HTTP::CookieMonster']` from ES comes back as: `'HTTP::CookieMonster::Cookie','HTTP::CookieMonster` and not the other way around like in Perl.

@clintongormley - any pro tips?

**Comment by clintongormley** [comment]
You're sorting on an `analyzed` field, while you should be sorting on a `not_analyzed` field:

    PUT t
    {
      "mappings": {
        "t": {
          "properties": {
            "text": {
              "type": "string",
              "fields": {
                "keyword": {
                  "type": "string",
                  "index": "not_analyzed"
                }
              }
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "text": "HTTP::CookieMonster::Cookie"
    }
    
    PUT t/t/2
    {
      "text": "HTTP::CookieMonster"
    }

this sorts on the analyzed field, so is actually using `cookie` and `cookiemonster` as the sort values:

    GET _search?sort=text

this sorts on the not_analyzed field, and so uses the full `HTTP::CookieMonster(::Cookie)` values
    
    GET _search?sort=text.keyword

**Comment by mickeyn** [comment]
@clintongormley thanks, the mapping we had seems wrongly set following some recent changes.
I think this will be resolved by the referenced PR.

**Comment by mickeyn** [comment]
@clintongormley is there a way for us to update the mapping for one field without doing a full reindex?

**Comment by mickeyn** [comment]
nm, read https://www.elastic.co/blog/changing-mapping-with-zero-downtime ... our upgrade to multi-type needs the re-index for the old data.

**Comment by mickeyn** [comment]
@clintongormley thanks again for a very quick & helpful response

**Comment by clintongormley** [comment]
@mickeyn if you're on 2.3, you can use the reindex API: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-reindex.html
