### ISSUE TITLE
Author search auto-complete is under "Products" label

### ISSUE THREAD

**Issue by xsawyerx** [CPAN-API/metacpan-web#1707]
[This applies to v1 too.]

Select "Authors" in the search box radio button. Write some author's name so auto-complete kicks in. The names appear under the label "Products".

**Comment by oalders** [comment]
@xsawyerx Thanks! Could you attach a screen shot?

**Comment by xsawyerx** [comment]
![metacpan-product](https://cloud.githubusercontent.com/assets/54725/15933825/84493ca6-2e61-11e6-9fa1-55634c2d81d1.png)

**Comment by oalders** [comment]
Wow.  I never noticed that before.  @danmcc is it possible to change that heading to "Authors"?

**Comment by danmcc** [comment]
Definitely!  You can do it via CSS:

```
#autocomplete-direct-results:before {
  content: 'Authors'
}
```

Looks like `root/static/css/jquery.autocomplete.css` is the place to put it.

**Comment by xsawyerx** [comment]
Fix merged. Closing.

Thank you. :)
