### ISSUE TITLE
v1 "++" list mangled

### ISSUE THREAD

**Issue by kentfredric** [CPAN-API/metacpan-web#1712]
https://v1.metacpan.org/release/ABIGAIL/Regexp-Common-2016052803
vs
https://metacpan.org/release/ABIGAIL/Regexp-Common-2016052803

![snapshot241](https://cloud.githubusercontent.com/assets/44790/15938847/0519854a-2ec9-11e6-81b3-add3d718afe0.png)
![snapshot242](https://cloud.githubusercontent.com/assets/44790/15938848/0519dc5c-2ec9-11e6-9932-ab3e94f209a6.png)

The HTML Links on the first set all link to `/author/` as well, which 404s.

**Comment by mickeyn** [comment]
should be fixed. please verify.

**Comment by kentfredric** [comment]
Verified.
