### ISSUE TITLE
Type-based searches à la search.cpan.org

### ISSUE THREAD

**Issue by joelbernstein** [CPAN-API/metacpan-web#287]
s.c.o allows querying by "type" (module, distribution, author) which restricts results to only come from the specified type of resource.
I find this a very useful feature and have a number of browser quicksearches which rely on it.
I can't figure out how to achieve the same thing using metacpan.

Examples:
1) search for distributions matching DBIx::Class, without listing modules therein
2) search for modules matching DBIx::Class, ignoring which dist they are in
3) search for ACME as an author, ignoring any Acme:: modules
4) search for Acme modules, ignoring an author whose name contains 'acme'

**Comment by ranguard** [comment]
No action - closing... again... still on wishlist
