### ISSUE TITLE
Allow "subscription" to modules for notification

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-web#327]
I'd like to be able to "subscribe" to several modules or distributions and get notified (by e-mail or via an RSS feed) when new versions of those modules are uploaded.

Extra bonus would be to be alerted that the list of dependencies has changed.

I'd also like to be notified when one of the dependencies of the modules I "subscribed" to is uploaded.

**Comment by ranguard** [comment]
Looks like done in #1230
