### ISSUE TITLE
`-TRIAL` dists don't show test results, and the matrix link is wrong

### ISSUE THREAD

**Issue by kentfredric** [CPAN-API/metacpan-web#886]
Reporting these problems as one bug, because I'd imagine their cause may be related. 

You'll note here: 

https://metacpan.org/release/KENTNL/File-ShareDir-ProjectDistDir-0.5.0-TRIAL

![](http://i39.tinypic.com/2lc9ugl.png][http://i39.tinypic.com/2lc9ugl.png)

There's no test reports

And the target link:
```html
http://matrix.cpantesters.org/?dist=File-ShareDir-ProjectDistDir+0.5.0
```

Takes you to a page with no results:

![](http://i43.tinypic.com/2aki59v.png)

However, there most certainly are results, 

![](http://i44.tinypic.com/206ov1i.png)

And if you look on the matrix image, you'll see there is an "other versions" element pointing to the `-TRIAL` release.

Its just that the link from metacpan is going to:

```
dist=File-ShareDir-ProjectDistDir+0.5.0
```
instead of 
```
dist=File-ShareDir-ProjectDistDir+0.5.0-TRIAL
```
![](http://i41.tinypic.com/2namkau.png)

**Comment by oalders** [comment]
Closing so that we can fix the testers data in https://github.com/CPAN-API/cpan-api/issues/471
