### ISSUE TITLE
Images in POD

### ISSUE THREAD

**Issue by dk** [CPAN-API/metacpan-web#935]
Hello all

I'd like to display images in my pod files, but the only way I found I can do this is embedding "img src" to an external resource. I don't quite like this because the resource can die, and because image versions itself can change. Ideally, "img src" should point to images contained in the same distribution.

Before you supported image as data URIs, but that doesn't dorm anymore. Is there any plan for image support? 

Thank you!

(ps Gabor started this http://perlmaven.com/how-to-add-images-to-cpan here so it's not just me)

**Comment by zmughal** [comment]
An example where the `data:` URI does not work is [here](https://metacpan.org/pod/release/ZMUGHAL/Devel-IPerl-0.002/example/20150209_IPerl_display_demo.pod).

**Comment by dk** [comment]
here are more examples: http://search.cpan.org/dist/Test-podimage/podimage.pm

**Comment by dk** [comment]
and here: https://metacpan.org/pod/Test::podimage

**Comment by zmughal** [comment]
I have a fix coming. HTML::Restrict needs to add the `data:` URI scheme to its allowed schemes.

**Comment by zmughal** [comment]
Fixed in the PR above.

**Comment by dk** [comment]
this is cool, thank you!

**Comment by zmughal** [comment]
This can now be closed. The changes are live! :fireworks:

**Comment by oalders** [comment]
@zmughal++
