### ISSUE TITLE
.pm file is missing from dist

### ISSUE THREAD

**Issue by karenetheridge** [CPAN-API/metacpan-web#945]
In this dist: https://metacpan.org/release/DOMM/Module-ExtractUse-0.32

There is no module nor executable listed in the release, and 'browse' does not reveal any either!  However, there are t/, xt/, example/ and lib/ files in the tarball.

It appears that all files that reside in a subdirectory are not visible.

**Comment by kentfredric** [comment]
Also affects version 0.33, for reasons unknown.

https://metacpan.org/release/DOMM/Module-ExtractUse-0.33

Somehow I got it in my head it was a MANIFEST problem ... but nope. MANIFEST looks fine.

**Comment by kentfredric** [comment]
More: Even though there are no visible problems with 0.31 ... only version 0.30 is recognised as "latest" by MetaCPAN.

But PAUSE and CPANMetaDB both see 0.33 as latest.

**Comment by rwstauner** [comment]
I reindexed all the releases and it looks to be fixed.
Any further issues?

**Comment by rwstauner** [comment]
Note: you may have to "Empty cache and hard refresh" as the Last-Modified header is wrong.
